"""Laser-mode counterparts to a subset of scripts/cam.py.

cam.py is built around spindle semantics (Z plunge, M3, peck cycles, depth
passes). A laser is fundamentally different: no Z motion, M4 dynamic
power, constant-depth centerline cuts, multi-pass for through-cut depth.

Rather than bolt a `head` discriminator into every cam.py op, we mirror
only the two ops that make sense for a diode laser:

    laser_profile(polygon, material, ...)       # mirrors cam.profile_cut
    laser_engrave(text, position, height, ...)  # mirrors cam.engrave_text

Refusals for pocket / drill / chamfer / face / slot are handled at the
CLI shim layer (scripts/cam_cli.py); this module just provides the two
emitters.

Emission style copies lessons/laser/05_test_card/test_card.py exactly:
;HEAD: laser, ;MATERIAL: <id>, $32=1, M4 S<power>, F<feed>, M5,
absolute mm, no Z motion. Validator-clean.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from shapely.geometry import MultiPolygon
from shapely.geometry.base import BaseGeometry

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from cam import (  # noqa: E402  (reuse glyph rasterizer + font helper)
    CamConfig,
    GcodeOutput,
    _find_default_font_path,
    _text_to_contours,
    _warn_or_fail,
)

PROFILES_DIR = SCRIPT_DIR.parent / "profiles"

_ENGRAVE_PX_PER_MM = 30


@dataclass
class LaserMaterial:
    id: str
    family: str
    thickness_mm: float
    power_percent: float
    feed_mm_per_min: int
    passes: int
    notes: str = ""


def load_laser_material(material_id: str) -> LaserMaterial:
    with (PROFILES_DIR / "laser_materials.yaml").open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            laser = m.get("laser") or {}
            if not laser:
                raise SystemExit(f"material '{material_id}' has no laser params")
            return LaserMaterial(
                id=m["id"],
                family=m.get("family", "unknown"),
                thickness_mm=float(m.get("thickness_mm", 0)),
                power_percent=float(laser["power_percent"]),
                feed_mm_per_min=int(laser["feed_mm_per_min"]),
                passes=int(laser.get("passes", 1)),
                notes=str(laser.get("notes", "")).strip(),
            )
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    raise SystemExit(f"unknown laser material: {material_id}. Available: {available}")


def _laser_header(op: str, material: LaserMaterial, cfg: CamConfig) -> list[str]:
    lines = [
        f"; {op} (laser) — generated by scripts/laser_cam.py",
        f"; material={material.id}  thickness={material.thickness_mm}mm",
        f"; power={material.power_percent}%  feed={material.feed_mm_per_min}mm/min"
        f"  passes={material.passes}",
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material.id}",
        f";TOOL: laser",
        "",
        "$32=1   ; enable GRBL laser mode",
        "G21     ; mm",
        "G90     ; absolute coordinates",
        "M5      ; laser off",
    ]
    return lines


def _laser_footer() -> list[str]:
    return ["M5  ; laser off", "G0 X0 Y0  ; park"]


def _power_s(power_percent: float) -> int:
    return int(round(power_percent * 10))  # percent -> S0..1000


def _polygon_rings(geom: BaseGeometry) -> list[list[tuple[float, float]]]:
    """Return all closed rings (exterior + interiors) of a Polygon or
    MultiPolygon as lists of (x, y) tuples. Each ring is closed (first
    point repeated at end)."""
    rings: list[list[tuple[float, float]]] = []
    if isinstance(geom, MultiPolygon):
        for sub in geom.geoms:
            rings.extend(_polygon_rings(sub))
        return rings
    if not hasattr(geom, "exterior"):
        raise ValueError(
            f"laser_profile expects a Polygon or MultiPolygon, got {type(geom).__name__}"
        )
    rings.append(list(geom.exterior.coords))
    for interior in geom.interiors:
        rings.append(list(interior.coords))
    return rings


def laser_profile(
    polygon: BaseGeometry,
    material: LaserMaterial,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Centerline cut around every ring of a polygon (exterior + holes).

    Laser kerf width = the beam itself, so the toolpath sits ON the
    polygon outline. Users wanting kerf-accurate finished dimensions
    should pre-offset the shape (shrink for OD, grow for ID) before
    passing it in. We don't auto-offset because the kerf depends on
    material, power, feed, and focus.

    Material.passes drives how many times each ring is re-traced (full
    through-cut depth control). M4 dynamic power means feed scales the
    actual delivered energy automatically.
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    rings = _polygon_rings(polygon)
    if not rings:
        _warn_or_fail("laser_profile: polygon has no rings to trace", cfg, warnings)
        return GcodeOutput(lines=[], warnings=warnings)

    s = _power_s(material.power_percent)
    feed = material.feed_mm_per_min
    passes = max(1, material.passes)

    lines = _laser_header("laser_profile", material, cfg)
    lines.append(f"; {len(rings)} ring(s), {passes} pass(es) per ring at S{s} F{feed}")
    lines.append("")

    for ri, ring in enumerate(rings, start=1):
        if len(ring) < 3:
            continue
        x0, y0 = ring[0]
        lines.append(f"; --- ring {ri}/{len(rings)} ({len(ring)} pts) ---")
        lines.append(f"M5")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"M4 S{s}")
        lines.append(f"F{feed}")
        for p in range(passes):
            if passes > 1:
                lines.append(f"; pass {p + 1}/{passes}")
            for x, y in ring[1:]:
                lines.append(f"G1 X{x:.3f} Y{y:.3f}")
            # If multi-pass, the path is already closed (ring[-1] == ring[0])
            # so the next pass starts naturally without a G0 reposition.
        lines.append("M5")
        lines.append("")

    lines.extend(_laser_footer())
    return GcodeOutput(lines=lines, warnings=warnings)


def laser_engrave(
    text: str,
    position: tuple[float, float],
    height_mm: float,
    material: LaserMaterial,
    font_path: str | None = None,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Outline-trace a text label at constant power.

    Reuses cam._text_to_contours so glyph geometry is identical to the
    spindle engrave_text op. Each closed contour becomes one M4 ... M5
    cycle. material.passes is respected (re-traces each contour N times).
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if not text:
        _warn_or_fail(
            "laser_engrave called with empty text; no output emitted.",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    if font_path is not None and not Path(font_path).exists():
        _warn_or_fail(
            f"font_path {font_path!r} not found; falling back to platform default.",
            cfg,
            warnings,
        )
        font_path = None
    if font_path is None:
        font_path = _find_default_font_path()
        if font_path is None:
            _warn_or_fail(
                "no system font found; pass font_path=... to a .ttf/.ttc/.otf",
                cfg,
                warnings,
            )
            return GcodeOutput(lines=[], warnings=warnings)

    contours = _text_to_contours(text, font_path, height_mm, _ENGRAVE_PX_PER_MM)
    if not contours:
        _warn_or_fail(
            f"laser_engrave: text={text!r} at height={height_mm}mm produced no contours",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    s = _power_s(material.power_percent)
    feed = material.feed_mm_per_min
    passes = max(1, material.passes)
    x_origin, y_origin = position

    lines = _laser_header("laser_engrave", material, cfg)
    lines.append(f"; text={text!r}  height={height_mm}mm  font={Path(font_path).name}")
    lines.append(
        f"; {len(contours)} closed contour(s), {passes} pass(es), S{s} F{feed}"
    )
    lines.append("")

    for ci, contour in enumerate(contours, start=1):
        if len(contour) < 3:
            continue
        x0, y0 = contour[0]
        lines.append(f"; --- contour {ci}/{len(contours)} ({len(contour)} pts) ---")
        lines.append("M5")
        lines.append(f"G0 X{x_origin + x0:.3f} Y{y_origin + y0:.3f}")
        lines.append(f"M4 S{s}")
        lines.append(f"F{feed}")
        for p in range(passes):
            if passes > 1:
                lines.append(f"; pass {p + 1}/{passes}")
            for x, y in contour[1:]:
                lines.append(f"G1 X{x_origin + x:.3f} Y{y_origin + y:.3f}")
        lines.append("M5")
        lines.append("")

    lines.extend(_laser_footer())
    return GcodeOutput(lines=lines, warnings=warnings)
