"""Laser-mode counterparts to a subset of scripts/cam.py.

cam.py is built around spindle semantics (Z plunge, M3, peck cycles, depth
passes). A laser is fundamentally different: no Z motion, constant-depth
centerline cuts, multi-pass for through-cut depth.

Rather than bolt a `head` discriminator into every cam.py op, we mirror
only the two ops that make sense for a diode laser:

    laser_profile(polygon, material, ...)       # mirrors cam.profile_cut
    laser_engrave(text, position, height, ...)  # mirrors cam.engrave_text

Refusals for pocket / drill / chamfer / face / slot are handled at the
CLI shim layer (scripts/cam_cli.py); this module just provides the two
emitters.

Power mode (this repo cuts with a weak ~10W diode):
  mode="static" (default): M3 constant power. A weak diode wants static
      power — it never reaches cutting threshold otherwise, so this is the
      diode-correct default and needs no special validator header.
  mode="dynamic": M4 dynamic power, S scaled with actual feed. This is the
      opt-in that UNDER-FIRES a weak diode (power drops with feed, so short
      segments and corners barely fire). Only use it if you know your diode
      can drive M4. It emits a ";LASER_MODE: dynamic" header so
      gcode_validate.py allows M4 (M4 is a violation without it).

Closed-loop technique (shared with quickcut/svg2gcode.py):
  Every ring/contour here is a CLOSED loop, which already returns to its own
  start — so there is NO laser-on return chord to avoid and ping-pong is
  wrong. We trace N SAME-DIRECTION laps, then FOLLOW THROUGH past the start
  so the cold-started first millimetres get re-cut hot and the part releases
  with no snag. The motion primitives (decimate, follow_through) come from
  the shared quickcut/motion.py so the diode know-how lives in one place.

Emission style is the standard validator-clean laser header used across the
repo's laser emitters:
;HEAD: laser, ;MATERIAL: <id>, $32=1, M3|M4 S<power>, F<feed>, M5,
absolute mm, no Z motion. Validator-clean.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import yaml
from shapely.geometry import MultiPolygon
from shapely.geometry.base import BaseGeometry

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from cam import (  # noqa: E402  (reuse glyph rasterizer + font helper)
    CamConfig,
    GcodeOutput,
    _find_default_font_path,
    _text_to_contours,
    _warn_or_fail,
)

# Shared weak-diode motion primitives (one source of truth across vibes tools).
sys.path.insert(0, str(SCRIPT_DIR.parent.parent / "quickcut"))
from motion import decimate, follow_through  # noqa: E402

PROFILES_DIR = SCRIPT_DIR.parent / "profiles"

_ENGRAVE_PX_PER_MM = 30

LaserMode = Literal["dynamic", "static"]


@dataclass
class LaserMaterial:
    id: str
    family: str
    thickness_mm: float
    power_percent: float
    feed_mm_per_min: int
    passes: int
    notes: str = ""


def load_laser_material(material_id: str) -> LaserMaterial:
    # laser_materials.yaml lives in the shared repo-root material_profiles/ dir.
    #
    # Not delegated to quickcut.materials.load_material: that returns only the
    # `laser` recipe block, but LaserMaterial also carries the entry's top-level
    # thickness_mm/family. Delegating would mean either a second file read or a
    # widened quickcut API, so the small self-contained read stays here.
    shared = SCRIPT_DIR.parent.parent / "material_profiles" / "laser_materials.yaml"
    with shared.open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            laser = m.get("laser") or {}
            if not laser:
                raise SystemExit(f"material '{material_id}' has no laser params")
            return LaserMaterial(
                id=m["id"],
                family=m.get("family", "unknown"),
                thickness_mm=float(m.get("thickness_mm", 0)),
                power_percent=float(laser["power_percent"]),
                feed_mm_per_min=int(laser["feed_mm_per_min"]),
                passes=int(laser.get("passes", 1)),
                notes=str(laser.get("notes", "")).strip(),
            )
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    raise SystemExit(f"unknown laser material: {material_id}. Available: {available}")


def _power_code(mode: LaserMode) -> str:
    return "M3" if mode == "static" else "M4"


def _laser_header(op: str, material: LaserMaterial, mode: LaserMode) -> list[str]:
    lines = [
        f"; {op} (laser, {mode}) — generated by scripts/laser_cam.py",
        f"; material={material.id}  thickness={material.thickness_mm}mm",
        f"; power={material.power_percent}%  feed={material.feed_mm_per_min}mm/min"
        f"  passes={material.passes}",
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material.id}",
        ";TOOL: laser",
    ]
    if mode == "dynamic":
        # The validator rejects M4 unless this header opts in. M4 scales power
        # with feed and under-fires a weak diode; static M3 is the default.
        lines.append(
            ";LASER_MODE: dynamic  (M4 — power scales with feed; under-fires a weak diode)"
        )
    lines += [
        "",
        "$32=1   ; enable GRBL laser mode",
        "G21     ; mm",
        "G90     ; absolute coordinates",
        "M5      ; laser off",
    ]
    return lines


def _laser_footer() -> list[str]:
    return ["M5  ; laser off", "G0 X0 Y0  ; park"]


def _power_s(power_percent: float, s_full_power: int) -> int:
    """Scale percent to an S word against the controller's full-power ceiling.

    Mirrors quickcut's CutJob.power_s: s_full_power must match GRBL $30 (the S
    value that means 100% PWM), so a 24000-step controller passes 50% -> S12000.
    """
    return round(power_percent / 100.0 * s_full_power)


def _closed_loop_motion(
    ring: list[tuple[float, float]], passes: int, warmup_mm: float
) -> list[str]:
    """Motion for one CLOSED loop (points already in absolute machine coords).

    A closed ring returns to its own start, so we trace it `passes` times in
    ONE direction (no ping-pong), then follow through past the start so the
    cold-cut start region is re-cut hot and the part releases with no snag.
    """
    lines: list[str] = []
    for p in range(1, passes + 1):
        if passes > 1:
            lines.append(f"; pass {p}/{passes}")
        lines += [f"G1 X{x:.3f} Y{y:.3f}" for x, y in ring[1:]]
    lead = follow_through(ring, warmup_mm)
    if lead:
        lines.append(f"; follow-through {warmup_mm:.1f}mm past start (clean release)")
        lines += [f"G1 X{x:.3f} Y{y:.3f}" for x, y in lead]
    return lines


def _polygon_rings(geom: BaseGeometry) -> list[list[tuple[float, float]]]:
    """Return all closed rings (exterior + interiors) of a Polygon or
    MultiPolygon as lists of (x, y) tuples. Each ring is closed (first
    point repeated at end)."""
    rings: list[list[tuple[float, float]]] = []
    if isinstance(geom, MultiPolygon):
        for sub in geom.geoms:
            rings.extend(_polygon_rings(sub))
        return rings
    if not hasattr(geom, "exterior"):
        raise ValueError(
            f"laser_profile expects a Polygon or MultiPolygon, got {type(geom).__name__}"
        )
    rings.append(list(geom.exterior.coords))
    for interior in geom.interiors:
        rings.append(list(interior.coords))
    return rings


def laser_profile(
    polygon: BaseGeometry,
    material: LaserMaterial,
    mode: LaserMode = "static",
    simplify_tolerance_mm: float = 0.05,
    min_segment_mm: float = 0.3,
    warmup_ms: float = 1000.0,
    s_full_power: int = 1000,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Centerline cut around every ring of a polygon (exterior + holes).

    Laser kerf width = the beam itself, so the toolpath sits ON the
    polygon outline. Users wanting kerf-accurate finished dimensions
    should pre-offset the shape (shrink for OD, grow for ID) before
    passing it in. We don't auto-offset because the kerf depends on
    material, power, feed, and focus.

    Material.passes drives how many times each ring is re-traced (full
    through-cut depth control). Every ring is CLOSED, so each is traced N
    same-direction laps then followed through past its start (see
    _closed_loop_motion) — no ping-pong.

    mode="static" (M3, default) holds S constant, which is what a weak diode
    needs to reach cutting threshold. mode="dynamic" (M4) scales power with
    feed and under-fires a weak diode; it emits a ";LASER_MODE: dynamic"
    header so the validator accepts M4.

    Geometry is thinned two ways before emission: simplify_tolerance_mm > 0
    runs shapely.simplify() to drop near-collinear vertices, then quickcut's
    decimate drops any points closer than min_segment_mm. s_full_power is the
    S value meaning 100% power (GRBL $30). warmup_ms sets the follow-through
    distance (warmup_ms/60000 * feed).
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if simplify_tolerance_mm > 0:
        polygon = polygon.simplify(simplify_tolerance_mm, preserve_topology=True)

    rings = _polygon_rings(polygon)
    if not rings:
        _warn_or_fail("laser_profile: polygon has no rings to trace", cfg, warnings)
        return GcodeOutput(lines=[], warnings=warnings)

    s = _power_s(material.power_percent, s_full_power)
    feed = material.feed_mm_per_min
    passes = max(1, material.passes)
    on = _power_code(mode)
    warmup_mm = warmup_ms / 60_000.0 * feed

    lines = _laser_header("laser_profile", material, mode)
    lines.append(
        f"; {len(rings)} ring(s), {passes} pass(es) per ring at S{s} F{feed} ({on})"
    )
    lines.append("")

    for ri, ring in enumerate(rings, start=1):
        ring = decimate(ring, min_segment_mm)
        if len(ring) < 3:
            continue
        x0, y0 = ring[0]
        lines.append(f"; --- ring {ri}/{len(rings)} ({len(ring)} pts) ---")
        lines.append("M5")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"{on} S{s}")
        lines.append(f"F{feed}")
        lines += _closed_loop_motion(ring, passes, warmup_mm)
        lines.append("M5")
        lines.append("")

    lines.extend(_laser_footer())
    return GcodeOutput(lines=lines, warnings=warnings)


def laser_engrave(
    text: str,
    position: tuple[float, float],
    height_mm: float,
    material: LaserMaterial,
    font_path: str | None = None,
    mode: LaserMode = "static",
    simplify_tolerance_mm: float = 0.05,
    min_segment_mm: float = 0.3,
    warmup_ms: float = 1000.0,
    s_full_power: int = 1000,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Outline-trace a text label at constant power.

    Reuses cam._text_to_contours so glyph geometry is identical to the
    spindle engrave_text op. Each closed contour becomes one M3/M4 ... M5
    cycle traced with the closed-loop technique (same-direction laps +
    follow-through). material.passes is respected.

    See laser_profile for mode, simplify_tolerance_mm, min_segment_mm,
    warmup_ms, and s_full_power semantics. The default mode="static" (M3) is
    the diode-correct choice; mode="dynamic" (M4) under-fires a weak diode.
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if not text:
        _warn_or_fail(
            "laser_engrave called with empty text; no output emitted.",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    if font_path is not None and not Path(font_path).exists():
        _warn_or_fail(
            f"font_path {font_path!r} not found; falling back to platform default.",
            cfg,
            warnings,
        )
        font_path = None
    if font_path is None:
        font_path = _find_default_font_path()
        if font_path is None:
            _warn_or_fail(
                "no system font found; pass font_path=... to a .ttf/.ttc/.otf",
                cfg,
                warnings,
            )
            return GcodeOutput(lines=[], warnings=warnings)

    contours = _text_to_contours(
        text,
        font_path,
        height_mm,
        _ENGRAVE_PX_PER_MM,
        simplify_tolerance_mm=simplify_tolerance_mm,
    )
    if not contours:
        _warn_or_fail(
            f"laser_engrave: text={text!r} at height={height_mm}mm produced no contours",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    s = _power_s(material.power_percent, s_full_power)
    feed = material.feed_mm_per_min
    passes = max(1, material.passes)
    on = _power_code(mode)
    x_origin, y_origin = position
    warmup_mm = warmup_ms / 60_000.0 * feed

    lines = _laser_header("laser_engrave", material, mode)
    lines.append(f"; text={text!r}  height={height_mm}mm  font={Path(font_path).name}")
    lines.append(
        f"; {len(contours)} closed contour(s), {passes} pass(es), S{s} F{feed} ({on})"
    )
    lines.append("")

    for ci, contour in enumerate(contours, start=1):
        # Move glyph into place, then treat as a closed loop.
        placed = [(x_origin + x, y_origin + y) for x, y in contour]
        placed = decimate(placed, min_segment_mm)
        if len(placed) < 3:
            continue
        x0, y0 = placed[0]
        lines.append(f"; --- contour {ci}/{len(contours)} ({len(placed)} pts) ---")
        lines.append("M5")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"{on} S{s}")
        lines.append(f"F{feed}")
        lines += _closed_loop_motion(placed, passes, warmup_mm)
        lines.append("M5")
        lines.append("")

    lines.extend(_laser_footer())
    return GcodeOutput(lines=lines, warnings=warnings)


def text_profile(
    text: str,
    position: tuple[float, float],
    height_mm: float,
    material: LaserMaterial,
    font_path: str | None = None,
    mode: LaserMode = "static",
    simplify_tolerance_mm: float = 0.05,
    min_segment_mm: float = 0.3,
    warmup_ms: float = 1000.0,
    s_full_power: int = 1000,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Cut each glyph's silhouette out of stock.

    Builds glyph polygons (with counters as holes via cam.text_to_polygons),
    translates them to `position`, unions into a MultiPolygon, and hands
    off to laser_profile — which already walks every exterior + interior
    ring, so 'O' and 'A' get their counters cut as well.

    Laser kerf width = the beam itself, so the toolpath is centerline
    (no offset). Pre-shrink/grow the text height if you need kerf-
    accurate finished dimensions. mode="static" (M3) is the diode-correct
    default; mode="dynamic" (M4) under-fires a weak diode.
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if not text:
        _warn_or_fail("text_profile: empty text; no output", cfg, warnings)
        return GcodeOutput(lines=[], warnings=warnings)

    if font_path is not None and not Path(font_path).exists():
        _warn_or_fail(
            f"font_path {font_path!r} not found; using platform default",
            cfg,
            warnings,
        )
        font_path = None
    if font_path is None:
        font_path = _find_default_font_path()
        if font_path is None:
            _warn_or_fail(
                "no system font found; pass font_path=... to a .ttf/.ttc/.otf",
                cfg,
                warnings,
            )
            return GcodeOutput(lines=[], warnings=warnings)

    # Import lazily so scripts/cam.py's text_to_polygons stays the single
    # source of truth for glyph polygonization (no duplicated cv2 code).
    from shapely.affinity import translate as _translate
    from shapely.geometry import MultiPolygon

    from cam import text_to_polygons

    glyphs = text_to_polygons(
        text,
        font_path,
        height_mm,
        _ENGRAVE_PX_PER_MM,
        simplify_tolerance_mm=simplify_tolerance_mm,
    )
    if not glyphs:
        _warn_or_fail(
            f"text_profile: text={text!r} at height={height_mm}mm produced no glyph polygons",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    x0, y0 = position
    moved = [_translate(g, xoff=x0, yoff=y0) for g in glyphs]
    geom = moved[0] if len(moved) == 1 else MultiPolygon(moved)

    # Hand off to laser_profile (which already handles MultiPolygon +
    # holes); we've already simplified, so skip the second simplify pass.
    out = laser_profile(
        geom,
        material,
        mode=mode,
        simplify_tolerance_mm=0,
        min_segment_mm=min_segment_mm,
        warmup_ms=warmup_ms,
        s_full_power=s_full_power,
        cfg=cfg,
    )
    # Tweak the header comment so the file is self-describing.
    if out.lines and out.lines[0].startswith("; laser_profile"):
        out.lines[0] = (
            f"; text_profile (laser, {mode}) — cuts each glyph silhouette out of stock"
        )
        # Insert text metadata after the existing material line so it stays
        # near the other header comments.
        out.lines.insert(
            3,
            f"; text={text!r}  height={height_mm}mm  font={Path(font_path).name}",
        )
    out.warnings.extend(warnings)
    return out
