"""Laser-mode counterparts to a subset of scripts/cam.py.

cam.py is built around spindle semantics (Z plunge, M3, peck cycles, depth
passes). A laser is fundamentally different: no Z motion, M3/M4 power,
constant-depth centerline cuts, multi-pass for through-cut depth.

Rather than bolt a `head` discriminator into every cam.py op, we mirror
only the two ops that make sense for a diode laser:

    laser_profile(polygon, material, ...)       # mirrors cam.profile_cut
    laser_engrave(text, position, height, ...)  # mirrors cam.engrave_text

Refusals for pocket / drill / chamfer / face / slot are handled at the
CLI shim layer (scripts/cam_cli.py); this module just provides the two
emitters.

Power mode:
  mode="dynamic" (default): M4 dynamic, S scales with actual feed.
      Safer for cuts because dwell at corners is auto-attenuated, BUT
      starves on very short segments (the laser never reaches programmed
      feed → effective S near zero). Combine with simplify_tolerance_mm
      to keep segments long enough.
  mode="static":  M3 static power. Use when M4 starves (over-sampled
      glyphs, dense contours) and the dwell-burn-through risk is
      acceptable (light-touch engraving on cardboard, etc.). Emits a
      ;LASER_MODE: static header so gcode_validate.py allows M3.

Emission style is the standard validator-clean laser header used across the
repo's laser emitters:
;HEAD: laser, ;MATERIAL: <id>, $32=1, M3|M4 S<power>, F<feed>, M5,
absolute mm, no Z motion. Validator-clean.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import yaml
from shapely.geometry import MultiPolygon
from shapely.geometry.base import BaseGeometry

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from cam import (  # noqa: E402  (reuse glyph rasterizer + font helper)
    CamConfig,
    GcodeOutput,
    _find_default_font_path,
    _text_to_contours,
    _warn_or_fail,
)

PROFILES_DIR = SCRIPT_DIR.parent / "profiles"

_ENGRAVE_PX_PER_MM = 30

LaserMode = Literal["dynamic", "static"]


@dataclass
class LaserMaterial:
    id: str
    family: str
    thickness_mm: float
    power_percent: float
    feed_mm_per_min: int
    passes: int
    notes: str = ""


def load_laser_material(material_id: str) -> LaserMaterial:
    with (PROFILES_DIR / "laser_materials.yaml").open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            laser = m.get("laser") or {}
            if not laser:
                raise SystemExit(f"material '{material_id}' has no laser params")
            return LaserMaterial(
                id=m["id"],
                family=m.get("family", "unknown"),
                thickness_mm=float(m.get("thickness_mm", 0)),
                power_percent=float(laser["power_percent"]),
                feed_mm_per_min=int(laser["feed_mm_per_min"]),
                passes=int(laser.get("passes", 1)),
                notes=str(laser.get("notes", "")).strip(),
            )
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    raise SystemExit(f"unknown laser material: {material_id}. Available: {available}")


def _power_code(mode: LaserMode) -> str:
    return "M3" if mode == "static" else "M4"


def _laser_header(op: str, material: LaserMaterial, mode: LaserMode) -> list[str]:
    lines = [
        f"; {op} (laser, {mode}) — generated by scripts/laser_cam.py",
        f"; material={material.id}  thickness={material.thickness_mm}mm",
        f"; power={material.power_percent}%  feed={material.feed_mm_per_min}mm/min"
        f"  passes={material.passes}",
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material.id}",
        ";TOOL: laser",
    ]
    if mode == "static":
        lines.append(
            ";LASER_MODE: static  (M3 — dwell-burn-through risk if motion stalls)"
        )
    lines += [
        "",
        "$32=1   ; enable GRBL laser mode",
        "G21     ; mm",
        "G90     ; absolute coordinates",
        "M5      ; laser off",
    ]
    return lines


def _laser_footer() -> list[str]:
    return ["M5  ; laser off", "G0 X0 Y0  ; park"]


def _power_s(power_percent: float) -> int:
    return int(round(power_percent * 10))  # percent -> S0..1000


def _polygon_rings(geom: BaseGeometry) -> list[list[tuple[float, float]]]:
    """Return all closed rings (exterior + interiors) of a Polygon or
    MultiPolygon as lists of (x, y) tuples. Each ring is closed (first
    point repeated at end)."""
    rings: list[list[tuple[float, float]]] = []
    if isinstance(geom, MultiPolygon):
        for sub in geom.geoms:
            rings.extend(_polygon_rings(sub))
        return rings
    if not hasattr(geom, "exterior"):
        raise ValueError(
            f"laser_profile expects a Polygon or MultiPolygon, got {type(geom).__name__}"
        )
    rings.append(list(geom.exterior.coords))
    for interior in geom.interiors:
        rings.append(list(interior.coords))
    return rings


def laser_profile(
    polygon: BaseGeometry,
    material: LaserMaterial,
    mode: LaserMode = "dynamic",
    simplify_tolerance_mm: float = 0.05,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Centerline cut around every ring of a polygon (exterior + holes).

    Laser kerf width = the beam itself, so the toolpath sits ON the
    polygon outline. Users wanting kerf-accurate finished dimensions
    should pre-offset the shape (shrink for OD, grow for ID) before
    passing it in. We don't auto-offset because the kerf depends on
    material, power, feed, and focus.

    Material.passes drives how many times each ring is re-traced (full
    through-cut depth control). mode="dynamic" (M4) scales delivered
    power with actual feed (corner-safe); mode="static" (M3) holds S
    constant (avoids the short-segment starvation gotcha).

    simplify_tolerance_mm > 0 runs shapely.simplify() to drop near-
    collinear vertices. Default 0.05mm keeps geometry visually identical
    but makes M4 dynamic mode practical even on circles/arcs that would
    otherwise emit hundreds of micro-segments.
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if simplify_tolerance_mm > 0:
        polygon = polygon.simplify(simplify_tolerance_mm, preserve_topology=True)

    rings = _polygon_rings(polygon)
    if not rings:
        _warn_or_fail("laser_profile: polygon has no rings to trace", cfg, warnings)
        return GcodeOutput(lines=[], warnings=warnings)

    s = _power_s(material.power_percent)
    feed = material.feed_mm_per_min
    passes = max(1, material.passes)
    on = _power_code(mode)

    lines = _laser_header("laser_profile", material, mode)
    lines.append(
        f"; {len(rings)} ring(s), {passes} pass(es) per ring at S{s} F{feed} ({on})"
    )
    lines.append("")

    for ri, ring in enumerate(rings, start=1):
        if len(ring) < 3:
            continue
        x0, y0 = ring[0]
        lines.append(f"; --- ring {ri}/{len(rings)} ({len(ring)} pts) ---")
        lines.append("M5")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"{on} S{s}")
        lines.append(f"F{feed}")
        for p in range(passes):
            if passes > 1:
                lines.append(f"; pass {p + 1}/{passes}")
            for x, y in ring[1:]:
                lines.append(f"G1 X{x:.3f} Y{y:.3f}")
        lines.append("M5")
        lines.append("")

    lines.extend(_laser_footer())
    return GcodeOutput(lines=lines, warnings=warnings)


def laser_engrave(
    text: str,
    position: tuple[float, float],
    height_mm: float,
    material: LaserMaterial,
    font_path: str | None = None,
    mode: LaserMode = "dynamic",
    simplify_tolerance_mm: float = 0.05,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Outline-trace a text label at constant power.

    Reuses cam._text_to_contours so glyph geometry is identical to the
    spindle engrave_text op. Each closed contour becomes one M3/M4 ... M5
    cycle. material.passes is respected.

    See laser_profile for mode and simplify_tolerance_mm semantics. The
    defaults (mode="dynamic", simplify=0.05mm) keep M4 working on glyph
    contours that would otherwise have ~1000 over-sampled points per letter
    — at 0.05mm tolerance, ~50 points per letter is plenty.
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if not text:
        _warn_or_fail(
            "laser_engrave called with empty text; no output emitted.",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    if font_path is not None and not Path(font_path).exists():
        _warn_or_fail(
            f"font_path {font_path!r} not found; falling back to platform default.",
            cfg,
            warnings,
        )
        font_path = None
    if font_path is None:
        font_path = _find_default_font_path()
        if font_path is None:
            _warn_or_fail(
                "no system font found; pass font_path=... to a .ttf/.ttc/.otf",
                cfg,
                warnings,
            )
            return GcodeOutput(lines=[], warnings=warnings)

    contours = _text_to_contours(
        text,
        font_path,
        height_mm,
        _ENGRAVE_PX_PER_MM,
        simplify_tolerance_mm=simplify_tolerance_mm,
    )
    if not contours:
        _warn_or_fail(
            f"laser_engrave: text={text!r} at height={height_mm}mm produced no contours",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    s = _power_s(material.power_percent)
    feed = material.feed_mm_per_min
    passes = max(1, material.passes)
    on = _power_code(mode)
    x_origin, y_origin = position

    lines = _laser_header("laser_engrave", material, mode)
    lines.append(f"; text={text!r}  height={height_mm}mm  font={Path(font_path).name}")
    lines.append(
        f"; {len(contours)} closed contour(s), {passes} pass(es), S{s} F{feed} ({on})"
    )
    lines.append("")

    for ci, contour in enumerate(contours, start=1):
        if len(contour) < 3:
            continue
        x0, y0 = contour[0]
        lines.append(f"; --- contour {ci}/{len(contours)} ({len(contour)} pts) ---")
        lines.append("M5")
        lines.append(f"G0 X{x_origin + x0:.3f} Y{y_origin + y0:.3f}")
        lines.append(f"{on} S{s}")
        lines.append(f"F{feed}")
        for p in range(passes):
            if passes > 1:
                lines.append(f"; pass {p + 1}/{passes}")
            for x, y in contour[1:]:
                lines.append(f"G1 X{x_origin + x:.3f} Y{y_origin + y:.3f}")
        lines.append("M5")
        lines.append("")

    lines.extend(_laser_footer())
    return GcodeOutput(lines=lines, warnings=warnings)


def text_profile(
    text: str,
    position: tuple[float, float],
    height_mm: float,
    material: LaserMaterial,
    font_path: str | None = None,
    mode: LaserMode = "dynamic",
    simplify_tolerance_mm: float = 0.05,
    cfg: CamConfig | None = None,
) -> GcodeOutput:
    """Cut each glyph's silhouette out of stock.

    Builds glyph polygons (with counters as holes via cam.text_to_polygons),
    translates them to `position`, unions into a MultiPolygon, and hands
    off to laser_profile — which already walks every exterior + interior
    ring, so 'O' and 'A' get their counters cut as well.

    Laser kerf width = the beam itself, so the toolpath is centerline
    (no offset). Pre-shrink/grow the text height if you need kerf-
    accurate finished dimensions.
    """
    cfg = cfg or CamConfig()
    warnings: list[str] = []

    if not text:
        _warn_or_fail("text_profile: empty text; no output", cfg, warnings)
        return GcodeOutput(lines=[], warnings=warnings)

    if font_path is not None and not Path(font_path).exists():
        _warn_or_fail(
            f"font_path {font_path!r} not found; using platform default",
            cfg,
            warnings,
        )
        font_path = None
    if font_path is None:
        font_path = _find_default_font_path()
        if font_path is None:
            _warn_or_fail(
                "no system font found; pass font_path=... to a .ttf/.ttc/.otf",
                cfg,
                warnings,
            )
            return GcodeOutput(lines=[], warnings=warnings)

    # Import lazily so scripts/cam.py's text_to_polygons stays the single
    # source of truth for glyph polygonization (no duplicated cv2 code).
    from shapely.affinity import translate as _translate
    from shapely.geometry import MultiPolygon

    from cam import text_to_polygons

    glyphs = text_to_polygons(
        text,
        font_path,
        height_mm,
        _ENGRAVE_PX_PER_MM,
        simplify_tolerance_mm=simplify_tolerance_mm,
    )
    if not glyphs:
        _warn_or_fail(
            f"text_profile: text={text!r} at height={height_mm}mm produced no glyph polygons",
            cfg,
            warnings,
        )
        return GcodeOutput(lines=[], warnings=warnings)

    x0, y0 = position
    moved = [_translate(g, xoff=x0, yoff=y0) for g in glyphs]
    geom = moved[0] if len(moved) == 1 else MultiPolygon(moved)

    # Hand off to laser_profile (which already handles MultiPolygon +
    # holes); we've already simplified, so skip the second pass.
    out = laser_profile(
        geom,
        material,
        mode=mode,
        simplify_tolerance_mm=0,
        cfg=cfg,
    )
    # Tweak the header comment so the file is self-describing.
    if out.lines and out.lines[0].startswith("; laser_profile"):
        out.lines[0] = (
            f"; text_profile (laser, {mode}) — cuts each glyph silhouette out of stock"
        )
        # Insert text metadata after the existing material line so it stays
        # near the other header comments.
        out.lines.insert(
            3,
            f"; text={text!r}  height={height_mm}mm  font={Path(font_path).name}",
        )
    out.warnings.extend(warnings)
    return out
