"""GCode emission for the jigsaw lesson.

Unifies what previously lived in three scratch scripts:
- phase6_small.emit_gcode (per-polygon cut, simple ordering)
- phase8_full_puzzle.emit_gcode (edge dedup via unary_union+linemerge,
  containment toposort: letter perimeters → interior → panel border last,
  greedy nearest-neighbor within tier)
- phase7_raster.emit_raster_gcode (M4 dynamic; G0 over white; G1 with
  per-run S for either halftone or grayscale)

Plus the three combined-output forms (raster only / cut only / combined)
from phase7. All emitters produce validator-clean GCode (HEAD/MATERIAL
headers, $32=1, M4 not M3, S in [0, 1000], coords within panel
envelope).

Coordinate convention: piece polygons come in image-pixel coords
(Y-down, panel inset by margin_px); emitter flips to machine mm (Y-up,
panel at 0,0). Conversion is centralized in img_to_machine_mm.
"""

from __future__ import annotations

import math
from itertools import groupby
from pathlib import Path

import yaml
from PIL import Image
from shapely.geometry import (
    GeometryCollection,
    LineString,
    MultiLineString,
    MultiPolygon,
    Polygon,
)
from shapely.ops import linemerge, unary_union

from geometry import PuzzleConfig

REPO_ROOT = Path(__file__).resolve().parent


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------


def load_material(material_id: str) -> dict:
    """Look up a material by id in profiles/laser_materials.yaml."""
    path = REPO_ROOT / "profiles" / "laser_materials.yaml"
    with path.open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            return m
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    raise SystemExit(f"unknown material: {material_id}. Available: {available}")


# ---------------------------------------------------------------------------
# Coord conversion (image px Y-down → machine mm Y-up)
# ---------------------------------------------------------------------------


def img_to_machine_mm(
    x_px: float, y_px: float, cfg: PuzzleConfig
) -> tuple[float, float]:
    """Image pixel coords (panel inset by margin_px, Y-down) to machine
    mm (panel at origin, Y-up). cfg.origin_offset_mm shifts the result —
    set it to (panel_mm/2, panel_mm/2) to center the panel on WCS origin
    instead of pinning the bottom-left corner there.

    The Y flip is about the FITTED panel height (puzzle_h_px), not the
    panel_h_mm bound: with fit_to_text the fitted banner is shorter than the
    bound, and using the bound would float the panel up by (bound - fit) in +Y.
    For non-fit configs puzzle_h_px/px_per_mm == panel_height_mm, so unchanged."""
    fitted_h_mm = cfg.puzzle_h_px / cfg.px_per_mm
    x_mm = (x_px - cfg.margin_px) / cfg.px_per_mm - cfg.origin_offset_mm[0]
    y_mm = (
        fitted_h_mm - (y_px - cfg.margin_px) / cfg.px_per_mm - cfg.origin_offset_mm[1]
    )
    return (x_mm, y_mm)


# ---------------------------------------------------------------------------
# GCode header / preamble
# ---------------------------------------------------------------------------


_PREAMBLE = (
    "$32=1   ; GRBL laser mode",
    "G21     ; mm",
    "G90     ; absolute",
    "M5      ; laser off",
    "G0 X0 Y0",
    "",
)


def _header(
    title: str,
    material_id: str,
    extra: list[str] | None = None,
    mode: str = "static",
) -> list[str]:
    out = [
        f"; {title}",
        f"; generated by emitter.py",
    ]
    if extra:
        out += [f"; {e}" for e in extra]
    out += [
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material_id}",
    ]
    if mode == "static":
        out.append(
            ";LASER_MODE: static  (M3 — dwell-burn-through risk if motion stalls)"
        )
    out += [
        "",
        *_PREAMBLE,
    ]
    return out


# ---------------------------------------------------------------------------
# Cut GCode: simple (per-polygon, no dedup) — for small puzzles
# ---------------------------------------------------------------------------


def _polygon_to_paths_mm(poly, cfg: PuzzleConfig) -> list[list[tuple[float, float]]]:
    """Exterior + holes of one polygon, in machine mm. Handles
    MultiPolygon / GeometryCollection recursively."""
    paths = []
    if isinstance(poly, Polygon):
        ext = [img_to_machine_mm(x, y, cfg) for x, y in poly.exterior.coords]
        paths.append(ext)
        for interior in poly.interiors:
            paths.append([img_to_machine_mm(x, y, cfg) for x, y in interior.coords])
    elif isinstance(poly, (MultiPolygon, GeometryCollection)):
        for sub in poly.geoms:
            if isinstance(sub, Polygon):
                paths.extend(_polygon_to_paths_mm(sub, cfg))
    return paths


def order_inside_out(pieces: list[dict]) -> list[dict]:
    """Letter pieces first (inside the cell pockets), then cells.
    Simple ordering for small puzzles; for full puzzles use the
    edge-based toposort below."""
    letters = [p for p in pieces if p.get("kind") == "letter"]
    cells = [p for p in pieces if p.get("kind") != "letter"]
    return letters + cells


def decimate_min_segment(
    pts: list[tuple[float, float]], min_seg_mm: float
) -> list[tuple[float, float]]:
    """Drop intermediate points that would create a segment shorter than
    min_seg_mm. Endpoints are always preserved (so closed rings stay
    closed). Guarantees every emitted segment is >= min_seg_mm, except a
    degenerate path that collapses to its two endpoints."""
    if min_seg_mm <= 0 or len(pts) < 3:
        return pts
    out = [pts[0]]
    for p in pts[1:]:
        lx, ly = out[-1]
        if math.hypot(p[0] - lx, p[1] - ly) >= min_seg_mm:
            out.append(p)
    # Force-preserve the final endpoint. If it was skipped because it sat
    # within min_seg of the last kept point, drop that kept point so the
    # closing segment is still >= min_seg.
    if out[-1] != pts[-1]:
        if len(out) >= 2:
            out.pop()
        out.append(pts[-1])
    return out


def _points_up_to(coords, dist):
    """Polyline from coords[0] forward along coords until arclength `dist`,
    ending at the interpolated point exactly at `dist` (or the last point if the
    path is shorter)."""
    out = [coords[0]]
    acc = 0.0
    for a, b in zip(coords, coords[1:]):
        seg = math.hypot(b[0] - a[0], b[1] - a[1])
        if acc + seg >= dist and seg > 1e-9:
            t = (dist - acc) / seg
            out.append((a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1])))
            return out
        out.append(b)
        acc += seg
    return out


def _warmup_wiggle(coords, warmup_mm):
    """Front-loaded diode warmup: motion points (starting AND ending at
    coords[0]) that trace back and forth over the START of the path so the laser
    reaches full power by the time it returns to coords[0] — then the real cut
    runs full-power over every mm, including this start zone.

    50/50 split: run forward warmup_mm/2, then back to the start (warmup_mm/2),
    so full power is hit exactly on the return. On a path too short for that,
    oscillate the whole path end-to-end until warmup_mm is covered, always
    landing back at coords[0]. Returns [] (no wiggle) if warmup_mm<=0.
    """
    if warmup_mm <= 0 or len(coords) < 2:
        return []
    total = 0.0
    for a, b in zip(coords, coords[1:]):
        total += math.hypot(b[0] - a[0], b[1] - a[1])
    if total <= 1e-9:
        return []
    half = warmup_mm / 2.0
    if total >= half:  # long enough: forward half, back to start
        fwd = _points_up_to(coords, half)
        return fwd[1:] + list(reversed(fwd))[1:]
    # short path: oscillate end-to-end (round trips return to start) until covered
    trips = max(1, math.ceil(warmup_mm / (2.0 * total)))
    seq = []
    for _ in range(trips):
        seq += list(coords[1:]) + list(reversed(coords))[1:]
    return seq


def emit_cut_gcode_simple(
    pieces: list[dict],
    material: dict,
    cfg: PuzzleConfig,
    word: str,
    mode: str = "static",
    feed_override: int | None = None,
    min_segment_mm: float = 0.0,
    power_percent: float | None = None,
) -> str:
    """Per-polygon cut, simple letter-then-cells ordering. Suitable for
    small-piece-count puzzles where edge dedup isn't worth the complexity.
    Shared cell-to-cell edges get cut twice; acceptable for ~5-piece
    tests.

    mode="dynamic" (default) emits M4 (power scales with feed); "static"
    emits M3 + a ;LASER_MODE: static header (constant power). feed_override
    replaces the material feedrate. min_segment_mm decimates points so no
    emitted segment is shorter than that distance. power_percent overrides
    the material power (S = percent*10). Diode cold-start fade is handled by
    lead-in overlap in emit_cut_gcode_full, not by dwells (GRBL laser mode
    fires only while moving)."""
    laser = material["laser"]
    pct = power_percent if power_percent is not None else laser["power_percent"]
    power_s = int(round(pct * 10))
    feed = feed_override if feed_override is not None else laser["feed_mm_per_min"]
    passes = laser["passes"]
    on = "M3" if mode == "static" else "M4"

    extra = [
        "loose-fit puzzle: centerline cuts, kerf becomes the clearance",
        "ASSUMES Z already at focal height in your WCS",
        "cut order: letters first, then cells (simple; shared edges cut twice)",
    ]
    if min_segment_mm > 0:
        extra.append(f"min segment: {min_segment_mm}mm (shorter chords decimated)")

    ordered = order_inside_out(pieces)
    lines = _header(
        title=f"small puzzle: word={word}, {len(pieces)} pieces, "
        f"{cfg.puzzle_w_px / cfg.px_per_mm:.0f}x{cfg.puzzle_h_px / cfg.px_per_mm:.0f}mm",
        material_id=material["id"],
        extra=extra,
        mode=mode,
    )

    for i, piece in enumerate(ordered, start=1):
        paths = _polygon_to_paths_mm(piece["polygon"], cfg)
        kind = piece.get("kind", "cell")
        for path_idx, pts in enumerate(paths):
            pts = decimate_min_segment(pts, min_segment_mm)
            if len(pts) < 3:
                continue
            label = f"{kind} {i}"
            if path_idx > 0:
                label += f" (hole {path_idx})"
            lines.append(f"; --- {label} ---")
            x0, y0 = pts[0]
            lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
            lines.append(f"{on} S{power_s}")
            lines.append(f"F{feed}")
            for pass_n in range(passes):
                if passes > 1:
                    lines.append(f"; pass {pass_n + 1} of {passes}")
                for x, y in pts[1:]:
                    lines.append(f"G1 X{x:.3f} Y{y:.3f}")
            lines.append("M5")
            lines.append("")
    lines += ["G0 X0 Y0", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cut GCode: edge-dedup with containment-aware ordering — for full puzzle
# ---------------------------------------------------------------------------


def extract_unique_edges(pieces: list[dict]) -> list[LineString]:
    """unary_union dedupes shared edges; linemerge combines collinear
    connected segments into continuous chains. Each interior edge
    appears exactly once in the output."""
    boundaries = [p["polygon"].boundary for p in pieces]
    merged = unary_union(boundaries)
    if isinstance(merged, (MultiLineString, GeometryCollection)):
        segs = [g for g in merged.geoms if isinstance(g, LineString)]
    elif isinstance(merged, LineString):
        segs = [merged]
    else:
        segs = []
    if len(segs) <= 1:
        return segs
    chained = linemerge(MultiLineString(segs))
    if isinstance(chained, LineString):
        return [chained]
    if isinstance(chained, MultiLineString):
        return list(chained.geoms)
    return [g for g in chained.geoms if isinstance(g, LineString)]


def classify_edge(
    edge: LineString,
    letter_polys: list[Polygon],
    cfg: PuzzleConfig,
    eps: float = 0.5,
) -> str:
    """Return 'letter', 'panel', or 'interior'. Panel edges lie on the
    panel rectangle; letter edges lie on a letter polygon's boundary;
    everything else is interior cell-to-cell."""
    coords = list(edge.coords)
    panel_x0 = cfg.margin_px
    panel_y0 = cfg.margin_px
    panel_w = cfg.puzzle_w_px
    panel_h = cfg.puzzle_h_px
    on_left = all(abs(x - panel_x0) < eps for x, _ in coords)
    on_right = all(abs(x - (panel_x0 + panel_w)) < eps for x, _ in coords)
    on_top = all(abs(y - panel_y0) < eps for _, y in coords)
    on_bottom = all(abs(y - (panel_y0 + panel_h)) < eps for _, y in coords)
    if on_left or on_right or on_top or on_bottom:
        return "panel"
    for lp in letter_polys:
        try:
            if edge.distance(lp.boundary) < eps:
                return "letter"
        except Exception:
            continue
    return "interior"


def greedy_order(
    edges: list[LineString], start_pt: tuple[float, float] = (0.0, 0.0)
) -> list[tuple[LineString, bool]]:
    """O(n²) greedy nearest-endpoint TSP. Returns (edge, reversed) per
    pick so the caller knows direction."""
    remaining = list(range(len(edges)))
    ordered: list[tuple[LineString, bool]] = []
    cur = start_pt
    while remaining:
        best_idx = None
        best_dist = float("inf")
        best_reverse = False
        for i in remaining:
            e = edges[i]
            c0 = e.coords[0]
            cn = e.coords[-1]
            d0 = (c0[0] - cur[0]) ** 2 + (c0[1] - cur[1]) ** 2
            dn = (cn[0] - cur[0]) ** 2 + (cn[1] - cur[1]) ** 2
            if d0 < best_dist:
                best_dist = d0
                best_idx = i
                best_reverse = False
            if dn < best_dist:
                best_dist = dn
                best_idx = i
                best_reverse = True
        e = edges[best_idx]
        coords = list(e.coords)
        if best_reverse:
            coords = coords[::-1]
            ordered.append((LineString(coords), True))
        else:
            ordered.append((e, False))
        cur = coords[-1]
        remaining.remove(best_idx)
    return ordered


def eulerian_order(
    edges: list[LineString],
    start_pt: tuple[float, float] = (0.0, 0.0),
    tol: float = 0.5,
    close_circuits: bool = True,
) -> list[tuple[LineString, bool]]:
    """Order edges as continuous trails so the laser walks THROUGH grid
    junctions without lifting. Returns (edge, reversed) like greedy_order;
    the downstream chainer fuses each trail into one continuous laser-on
    run.

    With close_circuits=True this runs a Chinese-Postman pass: odd-degree
    junctions (where letter pockets cross grid edges) are paired and the
    shortest connector between each pair is RE-TRACED, making every
    connected region an even-degree graph that Hierholzer covers in a
    single closed circuit. The re-traced segments just pass back over
    already-cut lines (harmless on cardboard) but keep the laser on, so a
    whole region cuts with one laser-on event instead of one per junction.
    """
    if not edges:
        return []

    def key(p):
        return (round(p[0] / tol), round(p[1] / tol))

    ends = [(key(e.coords[0]), key(e.coords[-1])) for e in edges]
    pt_of = {}
    for i, e in enumerate(edges):
        pt_of[ends[i][0]] = e.coords[0]
        pt_of[ends[i][1]] = e.coords[-1]

    from collections import defaultdict, deque
    import heapq

    # Multigraph edge list: (u, v, geom_idx). Duplicates (re-traced
    # connectors) append more entries pointing at the same geometry.
    medges = [(ends[i][0], ends[i][1], i) for i in range(len(edges))]

    def node_adj(active):
        a = defaultdict(list)
        for gi in active:
            u, v, _ = medges[gi]
            a[u].append(gi)
            a[v].append(gi)
        return a

    # Connected components over the original nodes.
    base_adj = node_adj(range(len(medges)))
    seen = set()
    components = []
    for n in list(base_adj):
        if n in seen:
            continue
        comp = []
        dq = deque([n])
        seen.add(n)
        while dq:
            x = dq.popleft()
            comp.append(x)
            for gi in base_adj[x]:
                for y in (medges[gi][0], medges[gi][1]):
                    if y not in seen:
                        seen.add(y)
                        dq.append(y)
        components.append(set(comp))

    def dijkstra(src, comp_nodes):
        dist = {src: 0.0}
        prev = {}  # node -> (prev_node, geom_idx)
        pq = [(0.0, src)]
        while pq:
            d, u = heapq.heappop(pq)
            if d > dist.get(u, 1e18):
                continue
            for gi in base_adj[u]:
                a, b, geom = medges[gi]
                w = edges[geom].length
                v = b if a == u else a
                nd = d + w
                if nd < dist.get(v, 1e18):
                    dist[v] = nd
                    prev[v] = (u, gi)
                    heapq.heappush(pq, (nd, v))
        return dist, prev

    if close_circuits:
        for comp in components:
            odd = [n for n in comp if len(base_adj[n]) % 2 == 1]
            if len(odd) < 2:
                continue
            # All-pairs shortest among odd nodes, then greedy nearest match.
            dmap = {}
            pmap = {}
            for o in odd:
                dmap[o], pmap[o] = dijkstra(o, comp)
            unmatched = set(odd)
            pairs = []
            while unmatched:
                a = min(unmatched, key=lambda n: (n[0], n[1]))
                unmatched.discard(a)
                best = None
                bestd = 1e18
                for b in unmatched:
                    dd = dmap[a].get(b, 1e18)
                    if dd < bestd:
                        bestd = dd
                        best = b
                if best is None:
                    continue
                unmatched.discard(best)
                pairs.append((a, best))
            # Duplicate the connector edges along each matched shortest path.
            for a, b in pairs:
                node = b
                while node != a and node in pmap[a]:
                    pn, gi = pmap[a][node]
                    u, v, geom = medges[gi]
                    medges.append((u, v, geom))  # re-traced connector
                    node = pn

    # Hierholzer over the (augmented) multigraph.
    adj = node_adj(range(len(medges)))
    used = [False] * len(medges)

    def walk(start):
        node_st = [start]
        edge_st = [None]
        out_nodes = []
        out_edges = []
        while node_st:
            v = node_st[-1]
            gi = None
            while adj[v]:
                cand = adj[v][-1]
                if used[cand]:
                    adj[v].pop()
                    continue
                gi = cand
                break
            if gi is None:
                out_nodes.append(node_st.pop())
                out_edges.append(edge_st.pop())
            else:
                used[gi] = True
                a, b, _ = medges[gi]
                other = b if a == v else a
                node_st.append(other)
                edge_st.append(gi)
        out_nodes.reverse()
        out_edges.reverse()
        directed = []
        for k in range(1, len(out_nodes)):
            gi = out_edges[k]
            a, _b, geom = medges[gi]
            directed.append((geom, a != out_nodes[k - 1]))
        return directed

    result: list[tuple[LineString, bool]] = []
    cur = start_pt
    remaining = set(range(len(medges)))
    while remaining:
        cand_nodes = set()
        for gi in remaining:
            if used[gi]:
                continue
            cand_nodes.add(medges[gi][0])
            cand_nodes.add(medges[gi][1])
        cand_nodes = {n for n in cand_nodes if any(not used[gi] for gi in adj[n])}
        if not cand_nodes:
            break
        odd = [
            n for n in cand_nodes if sum(1 for gi in adj[n] if not used[gi]) % 2 == 1
        ]
        pool = odd or list(cand_nodes)
        start = min(
            pool,
            key=lambda n: (pt_of[n][0] - cur[0]) ** 2 + (pt_of[n][1] - cur[1]) ** 2,
        )
        trail = walk(start)
        remaining = {gi for gi in range(len(medges)) if not used[gi]}
        if not trail:
            continue
        for geom, rev in trail:
            e = edges[geom]
            if rev:
                result.append((LineString(list(e.coords)[::-1]), True))
            else:
                result.append((e, False))
        last_geom, last_rev = trail[-1]
        lc = list(edges[last_geom].coords)
        cur = lc[0] if last_rev else lc[-1]
    return result


def chain_contiguous_paths(
    ordered: list[tuple[LineString, bool]], tol_px: float = 0.5
) -> list[list[tuple[float, float]]]:
    """Fuse an ordered list of (edge, reversed) into continuous polylines.

    Consecutive edges whose join is within tol_px are concatenated into a
    single path so the laser cuts them in one uninterrupted stroke (one
    laser-on, no mid-line lift/re-fire). A new path
    starts only where the gap to the previous edge's end exceeds tol_px.

    Returns a list of point-lists (each a continuous path). Each edge's
    direction was already resolved by greedy_order; we honor it.
    """
    paths: list[list[tuple[float, float]]] = []
    cur: list[tuple[float, float]] = []
    for edge, _reversed in ordered:
        pts = list(edge.coords)
        if len(pts) < 2:
            continue
        if not cur:
            cur = list(pts)
            continue
        lx, ly = cur[-1]
        if math.hypot(pts[0][0] - lx, pts[0][1] - ly) <= tol_px:
            # contiguous — append, skipping the duplicated join point
            cur.extend(pts[1:])
        else:
            paths.append(cur)
            cur = list(pts)
    if cur:
        paths.append(cur)
    return paths


def _order_chains_min_travel(chains, start, panel_w, panel_h):
    """Reorder cut chains to minimize pen-up (laser-off) travel: greedy
    nearest-neighbor, entering each chain from whichever end is closest
    (reversing if needed). The panel-border loop(s) — chains whose bbox spans
    most of the panel — are kept LAST so the stock stays attached until the end.
    Cuts travel less and stop hopping across the whole panel between pieces."""

    def is_border(ch):
        xs = [p[0] for p in ch]
        ys = [p[1] for p in ch]
        return (max(xs) - min(xs) > 0.8 * panel_w) and (
            max(ys) - min(ys) > 0.8 * panel_h
        )

    border = [c for c in chains if is_border(c)]
    remaining = [c for c in chains if not is_border(c)]
    out = []
    cur = start
    while remaining:
        best_i, best_rev, best_d = 0, False, None
        for i, ch in enumerate(remaining):
            for rev in (False, True):
                p = ch[-1] if rev else ch[0]
                d = (p[0] - cur[0]) ** 2 + (p[1] - cur[1]) ** 2
                if best_d is None or d < best_d:
                    best_d, best_i, best_rev = d, i, rev
        ch = remaining.pop(best_i)
        if best_rev:
            ch = ch[::-1]
        out.append(ch)
        cur = ch[-1]
    return out + border


def emit_cut_gcode_full(
    pieces: list[dict],
    material: dict,
    cfg: PuzzleConfig,
    word: str,
    mode: str = "static",
    feed_override: int | None = None,
    min_segment_mm: float = 0.0,
    power_percent: float | None = None,
    ramp_ms: float = 1000.0,
) -> str:
    """Full-panel cut emission with edge dedup + containment-aware
    ordering. Shared cell-cell boundaries cut exactly once. Cut order:
    letter perimeters → interior cell-to-cell → panel border last (so
    stock stays attached until the very final cut).

    mode / feed_override / min_segment_mm / power_percent behave as in
    emit_cut_gcode_simple. Diode cold-start fade is handled by RAMP, not
    dwells (GRBL laser mode keeps the beam off while stationary): the first
    `ramp_ms` of every closed loop under-cut while the diode ramped, so
    after the loop closes (laser now hot) we re-trace that same distance.
    ramp length = ramp_ms/1000 * feed_mm_per_s, derived from the
    feedrate. Default 1000ms — conservative (better to overcut than under)."""
    laser = material["laser"]
    pct = power_percent if power_percent is not None else laser["power_percent"]
    power_s = int(round(pct * 10))
    feed = feed_override if feed_override is not None else laser["feed_mm_per_min"]
    passes = laser["passes"]
    on = "M3" if mode == "static" else "M4"
    # Ramp distance from the ramp duration at this feed (mm/min -> mm/s).
    lead_in_mm = max(0.0, ramp_ms) / 1000.0 * (feed / 60.0)

    edges = extract_unique_edges(pieces)
    letter_polys = [p["polygon"] for p in pieces if p["kind"] == "letter"]
    letters, interior, panel = [], [], []
    for e in edges:
        cat = classify_edge(e, letter_polys, cfg)
        if cat == "letter":
            letters.append(e)
        elif cat == "panel":
            panel.append(e)
        else:
            interior.append(e)

    start_pt = (cfg.margin_px, cfg.margin_px)
    # Eulerian routing keeps the laser cutting continuously through grid
    # junctions (fewest laser-on events), which matters when the diode
    # ramps up over the first few mm after every restart. Letters /
    # interior / panel are still ordered as tiers (panel last so stock
    # stays attached), but each tier is walked as continuous trails.
    ordered = (
        eulerian_order(letters, start_pt)
        + eulerian_order(interior, start_pt)
        + eulerian_order(panel, start_pt)
    )

    # Convert each ordered edge to machine mm (honoring greedy_order's
    # direction), then fuse contiguous edges into single continuous cuts so
    # the laser doesn't lift / re-dwell / re-fire mid-line. tol is in mm.
    ordered_mm = [
        (
            LineString([img_to_machine_mm(x, y, cfg) for x, y in edge.coords]),
            rev,
        )
        for edge, rev in ordered
    ]
    chains = chain_contiguous_paths(ordered_mm, tol_px=0.1)
    chains = _order_chains_min_travel(
        chains,
        start=(0.0, 0.0),
        panel_w=cfg.puzzle_w_px / cfg.px_per_mm,
        panel_h=cfg.puzzle_h_px / cfg.px_per_mm,
    )

    extra = [
        "loose-fit: centerline cuts, laser kerf becomes the clearance",
        "edge dedup: shared cell-cell boundaries cut exactly once",
        "cut order: letters first, interior next, panel border last",
        "contiguous edges fused into single continuous cuts (no per-edge re-fire)",
        "ASSUMES Z already at focal height in your WCS",
    ]
    if lead_in_mm > 0:
        extra.append(
            f"warmup: {ramp_ms:.0f}ms = {lead_in_mm:.1f}mm at F{feed}; each cut "
            "runs fwd half / back to start first (laser at full power on return), "
            "then cuts the whole path at full power"
        )
    if min_segment_mm > 0:
        extra.append(f"min segment: {min_segment_mm}mm (shorter chords decimated)")

    lines = _header(
        title=f"full puzzle: word={word}, "
        f"{cfg.puzzle_w_px / cfg.px_per_mm:.0f}x{cfg.puzzle_h_px / cfg.px_per_mm:.0f}mm, "
        f"{len(chains)} continuous cut paths ({len(ordered)} edges after dedup)",
        material_id=material["id"],
        extra=extra,
        mode=mode,
    )

    for idx, path_mm in enumerate(chains, start=1):
        coords_mm = decimate_min_segment(path_mm, min_segment_mm)
        if len(coords_mm) < 2:
            continue
        warm = _warmup_wiggle(coords_mm, lead_in_mm)  # ends back at coords_mm[0]
        x0, y0 = coords_mm[0]
        lines.append(f"; --- path {idx}/{len(chains)} ({len(coords_mm)} pts) ---")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"{on} S{power_s}")
        lines.append(f"F{feed}")
        for pass_n in range(passes):
            if passes > 1:
                lines.append(f"; pass {pass_n + 1} of {passes}")
            if pass_n > 0:
                lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
                lines.append(f"{on} S{power_s}")
            if pass_n == 0 and warm:  # cold-start warmup only on the first pass
                lines.append(
                    "; warmup: fwd half / back to start, then cut at full power"
                )
                for x, y in warm:
                    lines.append(f"G1 X{x:.3f} Y{y:.3f}")
            for x, y in coords_mm[1:]:
                lines.append(f"G1 X{x:.3f} Y{y:.3f}")
        lines.append("M5")
        lines.append("")
    lines += ["G0 X0 Y0", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Raster GCode (halftone or grayscale)
# ---------------------------------------------------------------------------


def runs_in_row(row: list[int]) -> list[tuple[int, int, int]]:
    """Group consecutive same-value pixels into (start, end_inclusive, value)."""
    out = []
    idx = 0
    for value, group in groupby(row):
        length = sum(1 for _ in group)
        out.append((idx, idx + length - 1, value))
        idx += length
    return out


def emit_raster_gcode(
    img: Image.Image,
    mode: str,
    cfg: PuzzleConfig,
    line_spacing_mm: float,
    engrave_power_pct: int,
    engrave_feed: int,
) -> list[str]:
    """Raster GCode: M4 dynamic; G0 over white; G1 with per-run S."""
    if img.mode != "L":
        img = img.convert("L")
    w, h = img.size
    pixels = img.load()
    max_s = int(round(engrave_power_pct * 10))

    lines = [
        f"; --- raster engrave: {mode}, {w}x{h} px @ {line_spacing_mm}mm/line ---",
        f"; max power S={max_s} ({engrave_power_pct}%), feed F={engrave_feed}",
        "M4 S0   ; arm dynamic-power mode; S in motion commands controls power",
        f"F{engrave_feed}",
    ]

    for row_idx in range(h):
        machine_y = cfg.panel_mm - (row_idx + 0.5) * line_spacing_mm
        if machine_y < 0 or machine_y > cfg.panel_mm:
            continue
        row = [pixels[x, row_idx] for x in range(w)]
        for start, end, val in runs_in_row(row):
            if val == 255:
                continue
            x_start = (start + 0.5) * line_spacing_mm
            x_end = (end + 0.5) * line_spacing_mm
            if mode == "halftone":
                s_val = max_s
            else:
                s_val = int(round((255 - val) / 255 * max_s))
                if s_val <= 0:
                    continue
            lines.append(f"G0 X{x_start:.3f} Y{machine_y:.3f}")
            lines.append(f"G1 X{x_end:.3f} Y{machine_y:.3f} S{s_val}")
    lines.append("M5  ; raster done")
    return lines


def combined_raster_and_cut(
    raster_lines: list[str],
    cut_block: str,
    material_id: str,
    image_label: str,
    mode: str,
) -> str:
    """One GCode file: header + raster + cut. Strips the cut block's own
    preamble so we don't duplicate headers."""
    head = _header(
        title=f"combined puzzle — image={image_label}, mode={mode}, then cut",
        material_id=material_id,
        extra=[
            "ASSUMES Z already at focal height. Same Z used for engrave + cut.",
            "If your focal height differs (e.g. red vs green spacer on LaserTree),",
            "run the _raster and _cut files separately and refocus between them.",
        ],
    )
    cut_lines = cut_block.splitlines()
    body_start = 0
    for i, ln in enumerate(cut_lines):
        if ln.startswith("G0 X0 Y0") and i < 20:
            body_start = i + 1
            break
    cut_body = cut_lines[body_start:]
    return (
        "\n".join(head + raster_lines + [""] + ["; --- cut phase ---"] + cut_body)
        + "\n"
    )


def raster_only_gcode(
    raster_lines: list[str], material_id: str, image_label: str, mode: str
) -> str:
    """Engrave-only GCode (raster pass + return to origin). Pair with
    cut_only_gcode if you want separated files."""
    head = _header(
        title=f"raster engrave only — image={image_label}, mode={mode}",
        material_id=material_id,
        extra=[
            "ASSUMES Z already at engraving focal height in your WCS.",
            "Run this file FIRST, verify, then run the _cut file.",
        ],
    )
    return "\n".join(head + raster_lines + ["", "G0 X0 Y0", ""]) + "\n"
