"""GCode emission for the jigsaw lesson.

Unifies what previously lived in three scratch scripts:
- phase6_small.emit_gcode (per-polygon cut, simple ordering)
- phase8_full_puzzle.emit_gcode (edge dedup via unary_union+linemerge,
  containment toposort: letter perimeters → interior → panel border last,
  greedy nearest-neighbor within tier)
- phase7_raster.emit_raster_gcode (M4 dynamic; G0 over white; G1 with
  per-run S for either halftone or grayscale)

Plus the three combined-output forms (raster only / cut only / combined)
from phase7. All emitters produce validator-clean GCode (HEAD/MATERIAL
headers, $32=1, M4 not M3, S in [0, 1000], coords within panel
envelope).

Coordinate convention: piece polygons come in image-pixel coords
(Y-down, panel inset by margin_px); emitter flips to machine mm (Y-up,
panel at 0,0). Conversion is centralized in img_to_machine_mm.
"""

from __future__ import annotations

import math
from itertools import groupby
from pathlib import Path

import yaml
from PIL import Image
from shapely.geometry import (
    GeometryCollection,
    LineString,
    MultiLineString,
    MultiPolygon,
    Polygon,
)
from shapely.ops import linemerge, unary_union

from geometry import PuzzleConfig

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------


def load_material(material_id: str) -> dict:
    """Look up a material by id in profiles/laser_materials.yaml."""
    path = REPO_ROOT / "profiles" / "laser_materials.yaml"
    with path.open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            return m
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    raise SystemExit(f"unknown material: {material_id}. Available: {available}")


# ---------------------------------------------------------------------------
# Coord conversion (image px Y-down → machine mm Y-up)
# ---------------------------------------------------------------------------


def img_to_machine_mm(
    x_px: float, y_px: float, cfg: PuzzleConfig
) -> tuple[float, float]:
    """Image pixel coords (panel inset by margin_px, Y-down) to machine
    mm (panel at origin, Y-up). cfg.origin_offset_mm shifts the result —
    set it to (panel_mm/2, panel_mm/2) to center the panel on WCS origin
    instead of pinning the bottom-left corner there."""
    x_mm = (x_px - cfg.margin_px) / cfg.px_per_mm - cfg.origin_offset_mm[0]
    y_mm = (
        cfg.panel_height_mm
        - (y_px - cfg.margin_px) / cfg.px_per_mm
        - cfg.origin_offset_mm[1]
    )
    return (x_mm, y_mm)


# ---------------------------------------------------------------------------
# GCode header / preamble
# ---------------------------------------------------------------------------


_PREAMBLE = (
    "$32=1   ; GRBL laser mode",
    "G21     ; mm",
    "G90     ; absolute",
    "M5      ; laser off",
    "G0 X0 Y0",
    "",
)


def _header(
    title: str,
    material_id: str,
    extra: list[str] | None = None,
    mode: str = "dynamic",
) -> list[str]:
    out = [
        f"; {title}",
        f"; generated by lessons/laser/03_jigsaw/emitter.py",
    ]
    if extra:
        out += [f"; {e}" for e in extra]
    out += [
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material_id}",
    ]
    if mode == "static":
        out.append(
            ";LASER_MODE: static  (M3 — dwell-burn-through risk if motion stalls)"
        )
    out += [
        "",
        *_PREAMBLE,
    ]
    return out


# ---------------------------------------------------------------------------
# Cut GCode: simple (per-polygon, no dedup) — for small puzzles
# ---------------------------------------------------------------------------


def _polygon_to_paths_mm(poly, cfg: PuzzleConfig) -> list[list[tuple[float, float]]]:
    """Exterior + holes of one polygon, in machine mm. Handles
    MultiPolygon / GeometryCollection recursively."""
    paths = []
    if isinstance(poly, Polygon):
        ext = [img_to_machine_mm(x, y, cfg) for x, y in poly.exterior.coords]
        paths.append(ext)
        for interior in poly.interiors:
            paths.append([img_to_machine_mm(x, y, cfg) for x, y in interior.coords])
    elif isinstance(poly, (MultiPolygon, GeometryCollection)):
        for sub in poly.geoms:
            if isinstance(sub, Polygon):
                paths.extend(_polygon_to_paths_mm(sub, cfg))
    return paths


def order_inside_out(pieces: list[dict]) -> list[dict]:
    """Letter pieces first (inside the cell pockets), then cells.
    Simple ordering for small puzzles; for full puzzles use the
    edge-based toposort below."""
    letters = [p for p in pieces if p.get("kind") == "letter"]
    cells = [p for p in pieces if p.get("kind") != "letter"]
    return letters + cells


def decimate_min_segment(
    pts: list[tuple[float, float]], min_seg_mm: float
) -> list[tuple[float, float]]:
    """Drop intermediate points that would create a segment shorter than
    min_seg_mm. Endpoints are always preserved (so closed rings stay
    closed). Guarantees every emitted segment is >= min_seg_mm, except a
    degenerate path that collapses to its two endpoints."""
    if min_seg_mm <= 0 or len(pts) < 3:
        return pts
    out = [pts[0]]
    for p in pts[1:]:
        lx, ly = out[-1]
        if math.hypot(p[0] - lx, p[1] - ly) >= min_seg_mm:
            out.append(p)
    # Force-preserve the final endpoint. If it was skipped because it sat
    # within min_seg of the last kept point, drop that kept point so the
    # closing segment is still >= min_seg.
    if out[-1] != pts[-1]:
        if len(out) >= 2:
            out.pop()
        out.append(pts[-1])
    return out


def emit_cut_gcode_simple(
    pieces: list[dict],
    material: dict,
    cfg: PuzzleConfig,
    word: str,
    mode: str = "dynamic",
    warmup_ms: int = 0,
    feed_override: int | None = None,
    min_segment_mm: float = 0.0,
    power_percent: float | None = None,
    warmup_ms_first: int | None = None,
) -> str:
    """Per-polygon cut, simple letter-then-cells ordering. Suitable for
    small-piece-count puzzles where edge dedup isn't worth the complexity.
    Shared cell-to-cell edges get cut twice; acceptable for ~5-piece
    tests.

    mode="dynamic" (default) emits M4 (power scales with feed); "static"
    emits M3 + a ;LASER_MODE: static header (constant power). warmup_ms>0
    inserts a G4 dwell after the laser turns on at the start of each path,
    defeating diode cold-start fade-in (dial it in with lesson 06's
    `--sweep warmup`). feed_override replaces the material feedrate.
    min_segment_mm decimates points so no emitted segment is shorter than
    that distance. power_percent overrides the material power (S =
    percent*10)."""
    laser = material["laser"]
    pct = power_percent if power_percent is not None else laser["power_percent"]
    power_s = int(round(pct * 10))
    feed = feed_override if feed_override is not None else laser["feed_mm_per_min"]
    passes = laser["passes"]
    on = "M3" if mode == "static" else "M4"
    warmup_s = max(0, warmup_ms) / 1000.0
    first_ms = warmup_ms if warmup_ms_first is None else warmup_ms_first
    first_s = max(0, first_ms) / 1000.0

    extra = [
        "loose-fit puzzle: centerline cuts, kerf becomes the clearance",
        "ASSUMES Z already at focal height in your WCS",
        "cut order: letters first, then cells (simple; shared edges cut twice)",
    ]
    if first_ms > 0 or warmup_ms > 0:
        extra.append(
            f"warmup: G4 P{first_s:.3f} on first cut, P{warmup_s:.3f} on the rest "
            "(diode cold-start)"
        )
    if min_segment_mm > 0:
        extra.append(f"min segment: {min_segment_mm}mm (shorter chords decimated)")

    ordered = order_inside_out(pieces)
    lines = _header(
        title=f"small puzzle: word={word}, {len(pieces)} pieces, "
        f"{cfg.panel_mm:.0f}x{cfg.panel_mm:.0f}mm",
        material_id=material["id"],
        extra=extra,
        mode=mode,
    )

    first_cut = True
    for i, piece in enumerate(ordered, start=1):
        paths = _polygon_to_paths_mm(piece["polygon"], cfg)
        kind = piece.get("kind", "cell")
        for path_idx, pts in enumerate(paths):
            pts = decimate_min_segment(pts, min_segment_mm)
            if len(pts) < 3:
                continue
            label = f"{kind} {i}"
            if path_idx > 0:
                label += f" (hole {path_idx})"
            lines.append(f"; --- {label} ---")
            x0, y0 = pts[0]
            lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
            lines.append(f"{on} S{power_s}")
            lines.append(f"F{feed}")
            dwell_s = first_s if first_cut else warmup_s
            if dwell_s > 0:
                lines.append(f"G4 P{dwell_s:.3f}  ; warmup")
            first_cut = False
            for pass_n in range(passes):
                if passes > 1:
                    lines.append(f"; pass {pass_n + 1} of {passes}")
                for x, y in pts[1:]:
                    lines.append(f"G1 X{x:.3f} Y{y:.3f}")
            lines.append("M5")
            lines.append("")
    lines += ["G0 X0 Y0", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cut GCode: edge-dedup with containment-aware ordering — for full puzzle
# ---------------------------------------------------------------------------


def extract_unique_edges(pieces: list[dict]) -> list[LineString]:
    """unary_union dedupes shared edges; linemerge combines collinear
    connected segments into continuous chains. Each interior edge
    appears exactly once in the output."""
    boundaries = [p["polygon"].boundary for p in pieces]
    merged = unary_union(boundaries)
    if isinstance(merged, (MultiLineString, GeometryCollection)):
        segs = [g for g in merged.geoms if isinstance(g, LineString)]
    elif isinstance(merged, LineString):
        segs = [merged]
    else:
        segs = []
    if len(segs) <= 1:
        return segs
    chained = linemerge(MultiLineString(segs))
    if isinstance(chained, LineString):
        return [chained]
    if isinstance(chained, MultiLineString):
        return list(chained.geoms)
    return [g for g in chained.geoms if isinstance(g, LineString)]


def classify_edge(
    edge: LineString,
    letter_polys: list[Polygon],
    cfg: PuzzleConfig,
    eps: float = 0.5,
) -> str:
    """Return 'letter', 'panel', or 'interior'. Panel edges lie on the
    panel rectangle; letter edges lie on a letter polygon's boundary;
    everything else is interior cell-to-cell."""
    coords = list(edge.coords)
    panel_x0 = cfg.margin_px
    panel_y0 = cfg.margin_px
    panel_w = cfg.puzzle_w_px
    panel_h = cfg.puzzle_h_px
    on_left = all(abs(x - panel_x0) < eps for x, _ in coords)
    on_right = all(abs(x - (panel_x0 + panel_w)) < eps for x, _ in coords)
    on_top = all(abs(y - panel_y0) < eps for _, y in coords)
    on_bottom = all(abs(y - (panel_y0 + panel_h)) < eps for _, y in coords)
    if on_left or on_right or on_top or on_bottom:
        return "panel"
    for lp in letter_polys:
        try:
            if edge.distance(lp.boundary) < eps:
                return "letter"
        except Exception:
            continue
    return "interior"


def greedy_order(
    edges: list[LineString], start_pt: tuple[float, float] = (0.0, 0.0)
) -> list[tuple[LineString, bool]]:
    """O(n²) greedy nearest-endpoint TSP. Returns (edge, reversed) per
    pick so the caller knows direction."""
    remaining = list(range(len(edges)))
    ordered: list[tuple[LineString, bool]] = []
    cur = start_pt
    while remaining:
        best_idx = None
        best_dist = float("inf")
        best_reverse = False
        for i in remaining:
            e = edges[i]
            c0 = e.coords[0]
            cn = e.coords[-1]
            d0 = (c0[0] - cur[0]) ** 2 + (c0[1] - cur[1]) ** 2
            dn = (cn[0] - cur[0]) ** 2 + (cn[1] - cur[1]) ** 2
            if d0 < best_dist:
                best_dist = d0
                best_idx = i
                best_reverse = False
            if dn < best_dist:
                best_dist = dn
                best_idx = i
                best_reverse = True
        e = edges[best_idx]
        coords = list(e.coords)
        if best_reverse:
            coords = coords[::-1]
            ordered.append((LineString(coords), True))
        else:
            ordered.append((e, False))
        cur = coords[-1]
        remaining.remove(best_idx)
    return ordered


def chain_contiguous_paths(
    ordered: list[tuple[LineString, bool]], tol_px: float = 0.5
) -> list[list[tuple[float, float]]]:
    """Fuse an ordered list of (edge, reversed) into continuous polylines.

    Consecutive edges whose join is within tol_px are concatenated into a
    single path so the laser cuts them in one uninterrupted stroke (one
    laser-on, one warmup dwell, no mid-line lift/re-fire). A new path
    starts only where the gap to the previous edge's end exceeds tol_px.

    Returns a list of point-lists (each a continuous path). Each edge's
    direction was already resolved by greedy_order; we honor it.
    """
    paths: list[list[tuple[float, float]]] = []
    cur: list[tuple[float, float]] = []
    for edge, _reversed in ordered:
        pts = list(edge.coords)
        if len(pts) < 2:
            continue
        if not cur:
            cur = list(pts)
            continue
        lx, ly = cur[-1]
        if math.hypot(pts[0][0] - lx, pts[0][1] - ly) <= tol_px:
            # contiguous — append, skipping the duplicated join point
            cur.extend(pts[1:])
        else:
            paths.append(cur)
            cur = list(pts)
    if cur:
        paths.append(cur)
    return paths


def emit_cut_gcode_full(
    pieces: list[dict],
    material: dict,
    cfg: PuzzleConfig,
    word: str,
    mode: str = "dynamic",
    warmup_ms: int = 0,
    feed_override: int | None = None,
    min_segment_mm: float = 0.0,
    power_percent: float | None = None,
    warmup_ms_first: int | None = None,
) -> str:
    """Full-panel cut emission with edge dedup + containment-aware
    ordering. Shared cell-cell boundaries cut exactly once. Cut order:
    letter perimeters → interior cell-to-cell → panel border last (so
    stock stays attached until the very final cut).

    mode / warmup_ms / feed_override / min_segment_mm / power_percent
    behave as in emit_cut_gcode_simple. warmup_ms_first (if set) is the
    dwell on the very first cut, when the diode is coldest; later cuts use
    the shorter warmup_ms."""
    laser = material["laser"]
    pct = power_percent if power_percent is not None else laser["power_percent"]
    power_s = int(round(pct * 10))
    feed = feed_override if feed_override is not None else laser["feed_mm_per_min"]
    passes = laser["passes"]
    on = "M3" if mode == "static" else "M4"
    warmup_s = max(0, warmup_ms) / 1000.0
    first_ms = warmup_ms if warmup_ms_first is None else warmup_ms_first
    first_s = max(0, first_ms) / 1000.0

    edges = extract_unique_edges(pieces)
    letter_polys = [p["polygon"] for p in pieces if p["kind"] == "letter"]
    letters, interior, panel = [], [], []
    for e in edges:
        cat = classify_edge(e, letter_polys, cfg)
        if cat == "letter":
            letters.append(e)
        elif cat == "panel":
            panel.append(e)
        else:
            interior.append(e)

    start_pt = (cfg.margin_px, cfg.margin_px)
    ordered = (
        greedy_order(letters, start_pt)
        + greedy_order(interior, start_pt)
        + greedy_order(panel, start_pt)
    )

    # Convert each ordered edge to machine mm (honoring greedy_order's
    # direction), then fuse contiguous edges into single continuous cuts so
    # the laser doesn't lift / re-dwell / re-fire mid-line. tol is in mm.
    ordered_mm = [
        (
            LineString([img_to_machine_mm(x, y, cfg) for x, y in edge.coords]),
            rev,
        )
        for edge, rev in ordered
    ]
    chains = chain_contiguous_paths(ordered_mm, tol_px=0.1)

    extra = [
        "loose-fit: centerline cuts, laser kerf becomes the clearance",
        "edge dedup: shared cell-cell boundaries cut exactly once",
        "cut order: letters first, interior next, panel border last",
        "contiguous edges fused into single continuous cuts (no per-edge re-fire)",
        "ASSUMES Z already at focal height in your WCS",
    ]
    if first_ms > 0 or warmup_ms > 0:
        extra.append(
            f"warmup: G4 P{first_s:.3f} on first cut, P{warmup_s:.3f} on the rest "
            "(diode cold-start)"
        )
    if min_segment_mm > 0:
        extra.append(f"min segment: {min_segment_mm}mm (shorter chords decimated)")

    lines = _header(
        title=f"full puzzle: word={word}, {cfg.panel_mm:.0f}x{cfg.panel_mm:.0f}mm, "
        f"{len(chains)} continuous cut paths ({len(ordered)} edges after dedup)",
        material_id=material["id"],
        extra=extra,
        mode=mode,
    )

    first_cut = True
    for idx, path_mm in enumerate(chains, start=1):
        coords_mm = decimate_min_segment(path_mm, min_segment_mm)
        if len(coords_mm) < 2:
            continue
        x0, y0 = coords_mm[0]
        lines.append(f"; --- path {idx}/{len(chains)} ({len(coords_mm)} pts) ---")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"{on} S{power_s}")
        lines.append(f"F{feed}")
        dwell_s = first_s if first_cut else warmup_s
        if dwell_s > 0:
            lines.append(f"G4 P{dwell_s:.3f}  ; warmup")
        first_cut = False
        for pass_n in range(passes):
            if passes > 1:
                lines.append(f"; pass {pass_n + 1} of {passes}")
            if pass_n > 0:
                lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
                lines.append(f"{on} S{power_s}")
            for x, y in coords_mm[1:]:
                lines.append(f"G1 X{x:.3f} Y{y:.3f}")
        lines.append("M5")
        lines.append("")
    lines += ["G0 X0 Y0", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Raster GCode (halftone or grayscale)
# ---------------------------------------------------------------------------


def runs_in_row(row: list[int]) -> list[tuple[int, int, int]]:
    """Group consecutive same-value pixels into (start, end_inclusive, value)."""
    out = []
    idx = 0
    for value, group in groupby(row):
        length = sum(1 for _ in group)
        out.append((idx, idx + length - 1, value))
        idx += length
    return out


def emit_raster_gcode(
    img: Image.Image,
    mode: str,
    cfg: PuzzleConfig,
    line_spacing_mm: float,
    engrave_power_pct: int,
    engrave_feed: int,
) -> list[str]:
    """Raster GCode: M4 dynamic; G0 over white; G1 with per-run S."""
    if img.mode != "L":
        img = img.convert("L")
    w, h = img.size
    pixels = img.load()
    max_s = int(round(engrave_power_pct * 10))

    lines = [
        f"; --- raster engrave: {mode}, {w}x{h} px @ {line_spacing_mm}mm/line ---",
        f"; max power S={max_s} ({engrave_power_pct}%), feed F={engrave_feed}",
        "M4 S0   ; arm dynamic-power mode; S in motion commands controls power",
        f"F{engrave_feed}",
    ]

    for row_idx in range(h):
        machine_y = cfg.panel_mm - (row_idx + 0.5) * line_spacing_mm
        if machine_y < 0 or machine_y > cfg.panel_mm:
            continue
        row = [pixels[x, row_idx] for x in range(w)]
        for start, end, val in runs_in_row(row):
            if val == 255:
                continue
            x_start = (start + 0.5) * line_spacing_mm
            x_end = (end + 0.5) * line_spacing_mm
            if mode == "halftone":
                s_val = max_s
            else:
                s_val = int(round((255 - val) / 255 * max_s))
                if s_val <= 0:
                    continue
            lines.append(f"G0 X{x_start:.3f} Y{machine_y:.3f}")
            lines.append(f"G1 X{x_end:.3f} Y{machine_y:.3f} S{s_val}")
    lines.append("M5  ; raster done")
    return lines


def combined_raster_and_cut(
    raster_lines: list[str],
    cut_block: str,
    material_id: str,
    image_label: str,
    mode: str,
) -> str:
    """One GCode file: header + raster + cut. Strips the cut block's own
    preamble so we don't duplicate headers."""
    head = _header(
        title=f"combined puzzle — image={image_label}, mode={mode}, then cut",
        material_id=material_id,
        extra=[
            "ASSUMES Z already at focal height. Same Z used for engrave + cut.",
            "If your focal height differs (e.g. red vs green spacer on LaserTree),",
            "run the _raster and _cut files separately and refocus between them.",
        ],
    )
    cut_lines = cut_block.splitlines()
    body_start = 0
    for i, ln in enumerate(cut_lines):
        if ln.startswith("G0 X0 Y0") and i < 20:
            body_start = i + 1
            break
    cut_body = cut_lines[body_start:]
    return (
        "\n".join(head + raster_lines + [""] + ["; --- cut phase ---"] + cut_body)
        + "\n"
    )


def raster_only_gcode(
    raster_lines: list[str], material_id: str, image_label: str, mode: str
) -> str:
    """Engrave-only GCode (raster pass + return to origin). Pair with
    cut_only_gcode if you want separated files."""
    head = _header(
        title=f"raster engrave only — image={image_label}, mode={mode}",
        material_id=material_id,
        extra=[
            "ASSUMES Z already at engraving focal height in your WCS.",
            "Run this file FIRST, verify, then run the _cut file.",
        ],
    )
    return "\n".join(head + raster_lines + ["", "G0 X0 Y0", ""]) + "\n"
