#!/usr/bin/env python3
"""Generate a small laser test card for kerf + tram + dimensional checks.

Cuts a square within a square: an outer perimeter and an inner perimeter
so you can measure BOTH the part you keep and the drop-out, and use the
difference to back out kerf width at this material+power+feed combo.

Default geometry (centered on WCS origin so you can position stock around
a known machine point rather than registering against a corner):

    +---------------------------+   y = +25
    |  outer cut (50x50mm)      |
    |   +-----------------+     |
    |   |                 |     |
    |   |  inner cut      |     |
    |   |  (30x30mm)      |     |
    |   |                 |     |
    |   +-----------------+     |
    |                           |
    +---------------------------+   y = -25
   x=-25                       x=+25

After cutting, measure with calipers:
  * Outer square's outside dim: expect 50.0 - kerf. Solve for kerf.
  * Inner drop-out's outside dim: expect 30.0 - kerf. Cross-check.
  * Outer square's wall thickness (50-30)/2 = 10mm. Confirms small-scale
    dimensional accuracy and any axis skew (front vs back wall thickness).
  * Diagonal vs diagonal: confirms square (no skew/tram error).

Industry-standard companion tests already in this repo:
  * Power x speed x passes grid:  lessons/laser/02_calibration/
  * Interactive Z / power / feed: lessons/integration/04_interactive_laser_cal/

Usage:
  python test_card.py --material cardboard_thin_1mm
  python test_card.py --outer 50 --inner 30 --material plywood_baltic_birch_3mm
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

LESSON_DIR = Path(__file__).resolve().parent
REPO_ROOT = LESSON_DIR.parent.parent.parent
PROFILES = REPO_ROOT / "profiles"


def load_material(material_id: str) -> dict:
    with (PROFILES / "laser_materials.yaml").open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            if "laser" not in m:
                sys.exit(f"error: material '{material_id}' has no laser params")
            return m
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    sys.exit(f"error: unknown material '{material_id}'. Available: {available}")


def _square(power_s: int, feed: int, passes: int, side_mm: float, label: str):
    """Emit a centered square cut at the given side length."""
    h = side_mm / 2.0
    lines = [
        "",
        f"; --- {label} (side {side_mm}mm, {passes} passes) ---",
        f"G0 X{-h:.3f} Y{-h:.3f}",
        f"M4 S{power_s}",
        f"F{feed}",
    ]
    for p in range(passes):
        lines.append(f"; {label} pass {p + 1} of {passes}")
        lines.extend(
            [
                f"G1 X{h:.3f} Y{-h:.3f}",
                f"G1 X{h:.3f} Y{h:.3f}",
                f"G1 X{-h:.3f} Y{h:.3f}",
                f"G1 X{-h:.3f} Y{-h:.3f}",
            ]
        )
    lines.append("M5")
    return lines


def generate_gcode(outer_mm: float, inner_mm: float, material: dict) -> str:
    if outer_mm <= 0 or inner_mm <= 0:
        sys.exit("error: dimensions must be positive")
    if inner_mm >= outer_mm:
        sys.exit(
            f"error: --inner ({inner_mm}) must be smaller than --outer ({outer_mm})"
        )

    laser = material["laser"]
    power_s = int(round(laser["power_percent"] * 10))
    feed = int(laser["feed_mm_per_min"])
    passes = int(laser["passes"])

    lines = [
        "; test_card.py - laser kerf + tram + dimensional test card",
        "; generated by lessons/laser/05_test_card/test_card.py",
        f"; outer={outer_mm}mm  inner={inner_mm}mm  material={material['id']}",
        f"; power={laser['power_percent']}%  feed={feed}mm/min  passes={passes}",
        "; WCS origin is the CENTER of the card",
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material['id']}",
        "",
        "$32=1   ; enable GRBL laser mode (sticky)",
        "G21     ; mm",
        "G90     ; absolute coordinates",
        "M5      ; laser off",
        "G0 X0 Y0",
    ]
    # Inner first so the drop-out doesn't shift after the outer cut releases.
    lines.extend(_square(power_s, feed, passes, inner_mm, "inner"))
    lines.extend(_square(power_s, feed, passes, outer_mm, "outer"))
    lines += ["", "G0 X0 Y0  ; park at WCS origin"]
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--outer", type=float, default=50.0, help="outer square side, mm (default 50)"
    )
    p.add_argument(
        "--inner", type=float, default=30.0, help="inner square side, mm (default 30)"
    )
    p.add_argument(
        "--material",
        default="cardboard_thin_1mm",
        help="material id from profiles/laser_materials.yaml",
    )
    p.add_argument("--out", type=Path, default=None)
    args = p.parse_args()

    if args.out is None:
        build = LESSON_DIR / "build"
        build.mkdir(exist_ok=True)
        args.out = (
            build / f"test_card_{args.material}_{args.outer:g}x{args.inner:g}.gcode"
        )
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)

    material = load_material(args.material)
    gcode = generate_gcode(args.outer, args.inner, material)
    args.out.write_text(gcode)
    print(f"-> wrote {args.out}")
    print(f"   validate: python cnc.py validate {args.out.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
