#!/usr/bin/env python3
"""Standalone etch calibration test: a grid of swatches, one per
(power_percent, feed_mm_per_min) combination, each filled with a
continuous boustrophedon (back-and-forth, laser never lifts mid-swatch)
raster at that exact setting, and labeled on the material itself with the
power/feed numbers (traced from a system font) so there's no separate
reference sheet to keep track of -- read the numbers off the cut piece.

Not part of the ring pipeline; standalone because it authors machine mm
directly rather than going through cfg/img_to_machine_mm.

    PYTHONPATH=. python3 scripts/etch_calibration.py > /tmp/etch_cal.gcode
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "quickcut"))

from PIL import Image, ImageDraw
import geometry as G

POWERS = [10, 15, 20, 25, 30]  # rows, percent
FEEDS = [1500, 2000, 2500, 3000]  # columns, mm/min

SWATCH_W = 15.0
SWATCH_H = 12.0
GAP = 5.0
LABEL_MARGIN_X = 16.0  # room for row (power) labels
LABEL_MARGIN_Y = 10.0  # room for column (feed) labels
LINE_SPACING = 0.4  # mm between raster fill lines


def _label_strokes(text, cap_mm, x0, y0):
    """Trace `text` with a system font, return strokes (list of point
    lists) positioned with their baseline at (x0, y0), in mm, small.
    Reuses geometry._trace_mask_polygons the same way ring_prototype's
    glyph_local does, just for a short numeric label instead of a ring
    letter."""
    font = G.find_font(int(cap_mm / 0.7 * 20), None)  # rough size guess
    gl, gt, gr, gb = font.getbbox(text)
    pad = 4
    w, h = int(gr - gl) + 2 * pad, int(gb - gt) + 2 * pad
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-gl + pad, -gt + pad), text, fill=255, font=font)
    poly = G._trace_mask_polygons(img)
    # font.getbbox is in px at whatever size we guessed; scale to cap_mm
    cap_px = gb - gt
    scale = cap_mm / max(cap_px, 1)
    strokes = []
    polys = poly.geoms if poly.geom_type == "MultiPolygon" else [poly]
    for p in polys:
        rings = [p.exterior] + list(p.interiors)
        for r in rings:
            strokes.append([
                (x0 + (px - pad) * scale, y0 - (py - pad) * scale)
                for px, py in r.coords
            ])
    return strokes


def build():
    lines = [
        "; Etch calibration grid -- plywood_baltic_birch_3mm scrap test",
        "; generated by scripts/etch_calibration.py",
        ";",
        "; Each swatch is etched at a DIFFERENT power/feed -- read the",
        "; etched numbers on the piece itself. Look for: a visible light-",
        "; to-medium brown mark, no smoke plume, nowhere near cutting",
        "; through. Too faint -> raise power. Charred/smoking/cut-through",
        "; -> lower power first, then raise feed. Pick the best-looking",
        "; cell and use ITS power_percent/feed_mm_per_min as the etch:",
        "; entry for this material in material_profiles/laser_materials.yaml.",
        ";",
        f"; rows (power %%): {POWERS}",
        f"; cols (feed mm/min): {FEEDS}",
        ";",
        ";HEAD: laser",
        ";MATERIAL: plywood_baltic_birch_3mm (scrap)",
        ";LASER_MODE: static",
        "",
        "$32=1   ; GRBL laser mode",
        "G21     ; mm",
        "G90     ; absolute",
        "M5      ; laser off",
        "G0 X0 Y0",
        "",
    ]

    grid_w = LABEL_MARGIN_X + len(FEEDS) * SWATCH_W + (len(FEEDS) - 1) * GAP
    grid_h = LABEL_MARGIN_Y + len(POWERS) * SWATCH_H + (len(POWERS) - 1) * GAP

    # Column headers (feed values), one per column, above the grid.
    for ci, feed in enumerate(FEEDS):
        x = LABEL_MARGIN_X + ci * (SWATCH_W + GAP)
        strokes = _label_strokes(str(feed), 5.0, x, grid_h - 2.0)
        lines.append(f"; --- column header {feed} ---")
        for s in strokes:
            if len(s) < 2:
                continue
            x0, y0 = s[0]
            lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
            lines.append("M3 S250")
            lines.append("F2000")
            for x1, y1 in s[1:]:
                lines.append(f"G1 X{x1:.3f} Y{y1:.3f}")
            lines.append("M5")

    # Row headers (power values), one per row, left of the grid.
    for ri, power in enumerate(POWERS):
        y = grid_h - LABEL_MARGIN_Y - ri * (SWATCH_H + GAP) - SWATCH_H / 2
        strokes = _label_strokes(f"{power}%", 5.0, 2.0, y + 2.0)
        lines.append(f"; --- row header {power}% ---")
        for s in strokes:
            if len(s) < 2:
                continue
            x0, y0 = s[0]
            lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
            lines.append("M3 S250")
            lines.append("F2000")
            for x1, y1 in s[1:]:
                lines.append(f"G1 X{x1:.3f} Y{y1:.3f}")
            lines.append("M5")

    # Swatches: boustrophedon fill, laser stays on for the whole swatch.
    for ri, power in enumerate(POWERS):
        for ci, feed in enumerate(FEEDS):
            x0 = LABEL_MARGIN_X + ci * (SWATCH_W + GAP)
            y0 = grid_h - LABEL_MARGIN_Y - ri * (SWATCH_H + GAP) - SWATCH_H
            power_s = int(round(power * 10))
            n_lines = max(2, int(SWATCH_H / LINE_SPACING))
            step = SWATCH_H / n_lines
            lines.append(f"; --- swatch power={power}% feed={feed} ---")
            lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
            lines.append(f"M3 S{power_s}")
            lines.append(f"F{feed}")
            cur_y = y0
            going_right = True
            for k in range(n_lines + 1):
                target_x = x0 + SWATCH_W if going_right else x0
                lines.append(f"G1 X{target_x:.3f} Y{cur_y:.3f}")
                if k < n_lines:
                    cur_y = y0 + (k + 1) * step
                    lines.append(f"G1 X{target_x:.3f} Y{cur_y:.3f}")
                going_right = not going_right
            lines.append("M5")
            lines.append("")

    lines += ["G0 X0 Y0", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    print(build())
