#!/usr/bin/env python3
"""Generate a router-cut spacer with four-diameter geometry.

Hybrid toolchain:
  - If the geometry is a plain cylindrical washer (all four diameters
    equal), emits a .gcode directly. Fully automated.
  - Otherwise (any face has different OD/ID than the opposite face),
    emits a .scad and .csg and prints FreeCAD CAM next-steps.

Always emits the .scad so you can visualize the part in OpenSCAD
regardless of which path was taken.

Usage:
  python mill_spacer.py --height 6 --od 8 --id 3.2

  python mill_spacer.py --height 12 \\
      --top-od 10 --bottom-od 14 \\
      --top-id 3.2 --bottom-id 3.2
"""

from __future__ import annotations

import argparse
import math
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

LESSON_DIR = Path(__file__).resolve().parent
REPO_ROOT = LESSON_DIR.parent.parent.parent
PROFILES = REPO_ROOT / "profiles"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from job_params import compute_derived, find_by_id, load_yaml  # noqa: E402


# Threshold for choosing helical bore vs peck drill for the hole.
# When id_at_top / tool_diameter > this, we can helical-bore comfortably.
HELICAL_RATIO_THRESHOLD = 2.5

# Pierce/spoilboard overcut for through-cuts (mm beyond stock bottom)
SPOILBOARD_OVERCUT = 0.2

# Tabs for the outer profile cut (so the part doesn't release mid-job)
TAB_COUNT = 4
TAB_WIDTH_MM = 5.0
TAB_HEIGHT_MM = 1.5

# Safe traverse Z above stock top (mm)
SAFE_Z = 5.0


def _load_machine() -> dict:
    return load_yaml(PROFILES / "anolex_4030_evo_ultra2.yaml")


def _load_tools() -> list[dict]:
    return load_yaml(PROFILES / "tools.yaml")


def _load_materials() -> list[dict]:
    return load_yaml(PROFILES / "materials.yaml")


def _is_cylindrical(
    top_od: float, bottom_od: float, top_id: float, bottom_id: float
) -> bool:
    return math.isclose(top_od, bottom_od, abs_tol=1e-6) and math.isclose(
        top_id, bottom_id, abs_tol=1e-6
    )


# ---- SCAD generation ------------------------------------------------------


def generate_scad(
    top_od: float,
    bottom_od: float,
    top_id: float,
    bottom_id: float,
    height: float,
) -> str:
    return f"""// mill_spacer.scad
// generated by lessons/mill/01_spacer/mill_spacer.py
// height={height}  top_od={top_od}  bottom_od={bottom_od}  top_id={top_id}  bottom_id={bottom_id}

$fn = 128;

difference() {{
    cylinder(r1={bottom_od / 2}, r2={top_od / 2}, h={height});
    translate([0, 0, -0.1])
        cylinder(r1={bottom_id / 2}, r2={top_id / 2}, h={height + 0.2});
}}
"""


# ---- GCode generation (simple cylindrical case only) ----------------------


def _helical_bore_gcode(
    cx: float,
    cy: float,
    hole_dia: float,
    tool_dia: float,
    final_depth: float,
    feed_xy: int,
    plunge_feed: int,
    spindle_rpm: int,
) -> list[str]:
    """Helical bore: spiral down from Z=0 to final_depth at the hole center."""
    # The toolpath traces a circle whose radius is (hole_dia - tool_dia) / 2.
    # Each revolution descends by `pitch` mm. Use a conservative pitch so we
    # don't bog the tool.
    spiral_radius = (hole_dia - tool_dia) / 2
    pitch = tool_dia * 0.15  # mm per revolution; conservative

    n_revs = math.ceil(abs(final_depth) / pitch)

    start_x = cx + spiral_radius
    start_y = cy

    lines = [
        f"; helical bore (hole_dia={hole_dia}, tool_dia={tool_dia}, "
        f"spiral_radius={spiral_radius:.3f}, pitch={pitch:.3f})",
        f"G0 X{start_x:.3f} Y{start_y:.3f}",
        f"G0 Z{SAFE_Z:.3f}",
        f"M3 S{spindle_rpm}",
        f"G1 Z0 F{plunge_feed}",
    ]
    for rev in range(n_revs):
        z_at_end = max(final_depth, -(rev + 1) * pitch)
        # One full revolution (CCW) ending at slightly lower Z
        lines.append(
            f"G3 X{start_x:.3f} Y{start_y:.3f} Z{z_at_end:.3f} "
            f"I{-spiral_radius:.3f} J0 F{feed_xy}"
        )
    # Floor pass: one revolution at final depth to clean up
    lines.append(
        f"G3 X{start_x:.3f} Y{start_y:.3f} I{-spiral_radius:.3f} J0 F{feed_xy}"
    )
    # Retract
    lines += [
        f"G0 Z{SAFE_Z:.3f}",
        "M5",
    ]
    return lines


def _peck_drill_gcode(
    cx: float,
    cy: float,
    final_depth: float,
    peck_depth: float,
    plunge_feed: int,
    spindle_rpm: int,
) -> list[str]:
    """Peck drill at (cx, cy): plunge -> retract -> deeper plunge -> ..."""
    lines = [
        f"; peck drill (peck_depth={peck_depth:.3f})",
        f"G0 X{cx:.3f} Y{cy:.3f}",
        f"G0 Z{SAFE_Z:.3f}",
        f"M3 S{spindle_rpm}",
    ]
    z = 0.0
    while z > final_depth + 1e-6:
        z = max(final_depth, z - peck_depth)
        lines.append(f"G1 Z{z:.3f} F{plunge_feed}")
        lines.append(f"G0 Z{SAFE_Z:.3f}  ; retract for chip clearance")
    lines.append("M5")
    return lines


def _profile_with_tabs_gcode(
    cx: float,
    cy: float,
    od: float,
    tool_dia: float,
    final_depth: float,
    doc: float,
    feed_xy: int,
    plunge_feed: int,
    spindle_rpm: int,
) -> list[str]:
    """Profile-cut the outer perimeter with tabs."""
    # Toolpath radius (outside of part) = od/2 + tool_dia/2
    radius = od / 2 + tool_dia / 2
    start_x = cx + radius
    start_y = cy
    n_passes = math.ceil(abs(final_depth) / doc)
    # Tab depth: pass goes from Z=0 down to (Z=final_depth) but on the
    # final pass leaves TAB_HEIGHT_MM uncut at TAB_COUNT positions.
    # For MVP, simplify: emit all passes as full circles; tab handling
    # would require splitting the perimeter at tab locations. Mark this
    # as a TODO and emit a header comment so the user knows.

    lines = [
        f"; profile cut (outer perimeter, od={od}, tool_dia={tool_dia}, "
        f"radius={radius:.3f}, {n_passes} passes)",
        f"; TODO: tabs not yet implemented — part will release on the final pass.",
        f"; Hand-add an M0 pause before the last pass or clamp the part from below.",
        f"G0 X{start_x:.3f} Y{start_y:.3f}",
        f"G0 Z{SAFE_Z:.3f}",
        f"M3 S{spindle_rpm}",
        f"G1 Z0 F{plunge_feed}",
    ]
    for p in range(n_passes):
        z = max(final_depth, -(p + 1) * doc)
        lines.append(f"; perimeter pass {p + 1}/{n_passes} -> Z{z:.3f}")
        lines.append(f"G1 Z{z:.3f} F{plunge_feed}")
        lines.append(f"G3 X{start_x:.3f} Y{start_y:.3f} I{-radius:.3f} J0 F{feed_xy}")
    lines += [
        f"G0 Z{SAFE_Z:.3f}",
        "M5",
    ]
    return lines


def generate_cylindrical_gcode(
    od: float,
    id_mm: float,
    height: float,
    machine: dict,
    material: dict,
    tool: dict,
    spindle_rpm: int,
) -> str:
    """Generate full GCode for the cylindrical (degenerate) case."""
    tool_dia = tool["diameter_mm"]
    if id_mm < tool_dia - 1e-6:
        sys.exit(
            f"error: --id ({id_mm}) is smaller than tool diameter "
            f"({tool_dia}). Pick a smaller tool."
        )

    derived = compute_derived(machine, material, tool, spindle_rpm)
    feed_xy = int(round(derived["values"]["feed_xy_mm_per_min"]))
    plunge_feed = int(derived["values"]["plunge_feed_mm_per_min"])
    doc = derived["values"]["doc_rough_mm"]

    # Center the part with a margin from origin so the cut stays in
    # positive XY.
    margin = 5.0
    cx = od / 2 + margin
    cy = od / 2 + margin
    final_depth = -(height + SPOILBOARD_OVERCUT)

    header = [
        "; mill_spacer.py — cylindrical case (fully automated)",
        f"; height={height}  od={od}  id={id_mm}",
        f"; material={material['id']}  tool={tool['id']}  rpm={spindle_rpm}",
        f"; derived: feed_xy={feed_xy}  plunge={plunge_feed}  doc={doc:.3f}",
        ";",
        f";TOOL: {tool['id']}",
        f";MATERIAL: {material['id']}",
        "",
        "$32=0   ; ensure GRBL laser mode is OFF (spindle job)",
        "G21     ; mm",
        "G90     ; absolute coordinates",
        "M5      ; spindle off",
        f"G0 Z{SAFE_Z:.3f}  ; retract to safe Z before any XY motion",
        "G0 X0 Y0",
        "",
    ]

    body = []

    # ---- 1. Hole ----
    if id_mm > HELICAL_RATIO_THRESHOLD * tool_dia:
        body.append("; ==== 1. helical bore the hole ====")
        body.extend(
            _helical_bore_gcode(
                cx=cx,
                cy=cy,
                hole_dia=id_mm,
                tool_dia=tool_dia,
                final_depth=final_depth,
                feed_xy=feed_xy,
                plunge_feed=plunge_feed,
                spindle_rpm=spindle_rpm,
            )
        )
    else:
        body.append("; ==== 1. peck drill the hole ====")
        body.extend(
            _peck_drill_gcode(
                cx=cx,
                cy=cy,
                final_depth=final_depth,
                peck_depth=doc,
                plunge_feed=plunge_feed,
                spindle_rpm=spindle_rpm,
            )
        )

    # ---- 2. Outer perimeter ----
    body.append("")
    body.append("; ==== 2. profile cut the outer perimeter ====")
    body.extend(
        _profile_with_tabs_gcode(
            cx=cx,
            cy=cy,
            od=od,
            tool_dia=tool_dia,
            final_depth=final_depth,
            doc=doc,
            feed_xy=feed_xy,
            plunge_feed=plunge_feed,
            spindle_rpm=spindle_rpm,
        )
    )

    footer = [
        "",
        "M5",
        "G0 X0 Y0",
    ]

    return "\n".join(header + body + footer) + "\n"


# ---- 3D / frustum case ----------------------------------------------------


def _frustum_next_steps(scad_path: Path, csg_path: Path | None) -> str:
    return f"""
The geometry is not a plain cylinder (any of top_od/bottom_od/top_id/bottom_id
differ). This case needs FreeCAD CAM for the sloped wall(s).

Generated:
  SCAD:  {scad_path}
  CSG:   {csg_path if csg_path else "(openscad not on PATH; run it yourself)"}

Next steps:
  1. Open FreeCAD. Switch to the OpenSCAD workbench.
  2. File -> Import -> select {csg_path or "<your .csg>"}.
     You'll get a Part Solid in the tree.
  3. Switch to CAM workbench. CAM -> Job. Pick the Solid as Base.
  4. Stock: Box from base bounding box, no extra (model has real Z thickness).
  5. Set WCS origin: front-left-top of stock.
  6. Add a Tool Controller for a flat endmill (roughing) AND a ball-end
     mill (finishing) — sloped walls need ball-end finishing.
  7. Add operations:
     - Pocket (the hole) with the smaller flat endmill, leave 0.5mm stock.
     - Profile (outer) with the flat endmill, leave 0.5mm stock, tabs.
     - 3D Surface (finishing) with the ball-end mill on both walls.
  8. Post-process to GCode (CAM -> Post Processor -> grbl).
  9. cnc.py validate <gcode>
 10. cnc.py preflight <gcode>
 11. Run in gSender.
"""


def run_openscad(scad_path: Path, csg_path: Path) -> bool:
    openscad = (
        shutil.which("openscad") or "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"
    )
    if not Path(openscad).exists() and not shutil.which(openscad):
        return False
    cmd = [openscad, "-o", str(csg_path), str(scad_path)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0


# ---- main -----------------------------------------------------------------


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--height", type=float, default=6.0)
    p.add_argument(
        "--od",
        type=float,
        default=8.0,
        help="outer diameter; sets top-od and bottom-od unless overridden",
    )
    p.add_argument(
        "--id",
        type=float,
        default=3.2,
        help="inner diameter; sets top-id and bottom-id unless overridden",
    )
    p.add_argument("--top-od", type=float, default=None)
    p.add_argument("--bottom-od", type=float, default=None)
    p.add_argument("--top-id", type=float, default=None)
    p.add_argument("--bottom-id", type=float, default=None)
    p.add_argument("--material", default="plywood_baltic_birch_6mm")
    p.add_argument("--tool", default="flat_3.175mm_2flute")
    p.add_argument("--spindle-rpm", type=int, default=18000)
    p.add_argument("--out", type=Path, default=None)
    args = p.parse_args()

    top_od = args.top_od if args.top_od is not None else args.od
    bottom_od = args.bottom_od if args.bottom_od is not None else args.od
    top_id = args.top_id if args.top_id is not None else args.id
    bottom_id = args.bottom_id if args.bottom_id is not None else args.id

    for name, val in [
        ("top_od", top_od),
        ("bottom_od", bottom_od),
        ("top_id", top_id),
        ("bottom_id", bottom_id),
        ("height", args.height),
    ]:
        if val <= 0:
            sys.exit(f"error: {name} must be > 0 (got {val})")
    if top_id >= top_od or bottom_id >= bottom_od:
        sys.exit("error: hole diameter must be smaller than outer diameter")

    machine = _load_machine()
    materials = _load_materials()
    tools = _load_tools()
    material = find_by_id(materials, args.material, "material")
    tool = find_by_id(tools, args.tool, "tool")

    build_dir = LESSON_DIR / "build"
    build_dir.mkdir(exist_ok=True)
    stem = f"spacer_h{args.height}_to{top_od}_bo{bottom_od}_ti{top_id}_bi{bottom_id}"

    # Always emit the .scad
    scad_path = build_dir / f"{stem}.scad"
    scad_path.write_text(
        generate_scad(top_od, bottom_od, top_id, bottom_id, args.height)
    )
    print(f"-> wrote {scad_path}")

    if _is_cylindrical(top_od, bottom_od, top_id, bottom_id):
        # Simple cylindrical case: emit GCode directly.
        gcode_path = args.out or (build_dir / f"{stem}.gcode")
        gcode = generate_cylindrical_gcode(
            od=top_od,
            id_mm=top_id,
            height=args.height,
            machine=machine,
            material=material,
            tool=tool,
            spindle_rpm=args.spindle_rpm,
        )
        gcode_path.write_text(gcode)
        print(f"-> wrote {gcode_path}")
        print(
            "\nNext:\n"
            f"  python cnc.py validate {gcode_path}\n"
            f"  python cnc.py preflight {gcode_path}\n"
            "  (then load in gSender, install the tool, probe Z, run)\n"
        )
    else:
        # 3D / frustum case: run openscad if available and print next steps.
        csg_path = build_dir / f"{stem}.csg"
        ok = run_openscad(scad_path, csg_path)
        if not ok:
            csg_path = None
        print(_frustum_next_steps(scad_path, csg_path))


if __name__ == "__main__":
    main()
