#!/usr/bin/env python3
"""Generate GRBL laser-mode GCode for a parametric PCB spacer ring.

One ring per gcode file. Two concentric circles cut from sheet material.

Usage:
  python spacer.py --od 6.0 --id 3.2 \\
                   --material plywood_baltic_birch_3mm \\
                   --out build/spacer_od6_id3.2.gcode

Toolpath dimensions are NOT kerf-compensated. The finished hole will be
approximately kerf-width LARGER than --id; the finished outer diameter
will be approximately kerf-width SMALLER than --od. For a precise fit,
add ~0.15 mm to --id and subtract from --od yourself.

Output is GRBL laser-mode GCode (uses M4 dynamic power, $32=1, no Z
moves). Validate with `python cnc.py validate <gcode>` before running.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

LESSON_DIR = Path(__file__).resolve().parent
REPO_ROOT = LESSON_DIR.parent.parent.parent
PROFILES = REPO_ROOT / "profiles"


def load_material(material_id: str) -> dict:
    """Load a material from profiles/laser_materials.yaml or exit."""
    with (PROFILES / "laser_materials.yaml").open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            if "laser" not in m:
                sys.exit(
                    f"error: material '{material_id}' has no laser params "
                    f"in profiles/laser_materials.yaml"
                )
            return m
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    sys.exit(f"error: unknown material '{material_id}'. Available: {available}")


def generate_gcode(od_mm: float, id_mm: float, material: dict) -> str:
    """Render the .gcode text for one spacer ring."""
    if id_mm >= od_mm:
        sys.exit(f"error: --id ({id_mm}) must be smaller than --od ({od_mm})")
    if id_mm <= 0 or od_mm <= 0:
        sys.exit("error: dimensions must be positive")

    laser = material["laser"]
    power_s = int(round(laser["power_percent"] * 10))  # percent -> S0..1000
    feed = laser["feed_mm_per_min"]
    passes = laser["passes"]

    # Center the spacer at (od/2 + margin, od/2 + margin) so it sits
    # entirely in the positive quadrant with a small gap from the WCS
    # origin (which the user touches off to the stock front-left corner).
    margin = 2.0
    cx = od_mm / 2 + margin
    cy = od_mm / 2 + margin
    inner_r = id_mm / 2
    outer_r = od_mm / 2

    lines = [
        "; spacer.py — laser-cut PCB spacer ring",
        "; generated by lessons/laser/01_spacer/spacer.py",
        f"; OD={od_mm}mm  ID={id_mm}mm  material={material['id']}",
        ";",
        "; toolpath dimensions are NOT kerf-compensated:",
        f"; finished hole will be ~kerf wider than {id_mm}mm",
        f"; finished OD will be ~kerf narrower than {od_mm}mm",
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material['id']}",
        "",
        "$32=1   ; enable GRBL laser mode (sticky)",
        "G21     ; mm",
        "G90     ; absolute coordinates",
        "M5      ; laser off",
        "G0 X0 Y0  ; park at WCS origin",
        "",
        f"; --- inner cut (ID {id_mm}mm, {passes} passes) ---",
        f"G0 X{cx + inner_r:.3f} Y{cy:.3f}",
        f"M4 S{power_s}",
        f"F{feed}",
    ]
    for p in range(passes):
        lines.append(f"; inner pass {p + 1} of {passes}")
        lines.append(f"G3 X{cx + inner_r:.3f} Y{cy:.3f} I{-inner_r:.3f} J0")

    lines += [
        "M5",
        "",
        f"; --- outer cut (OD {od_mm}mm, {passes} passes) ---",
        f"G0 X{cx + outer_r:.3f} Y{cy:.3f}",
        f"M4 S{power_s}",
        f"F{feed}",
    ]
    for p in range(passes):
        lines.append(f"; outer pass {p + 1} of {passes}")
        lines.append(f"G3 X{cx + outer_r:.3f} Y{cy:.3f} I{-outer_r:.3f} J0")

    lines += [
        "M5",
        "",
        "G0 X0 Y0  ; park at WCS origin",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--od", type=float, default=6.0, help="outer diameter, mm (default: 6.0)"
    )
    p.add_argument(
        "--id",
        type=float,
        default=3.2,
        help="inner diameter, mm (default: 3.2 = M3 clearance)",
    )
    p.add_argument(
        "--material",
        default="plywood_baltic_birch_3mm",
        help="material id from profiles/laser_materials.yaml",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output .gcode path (default: build/spacer_<od>_<id>.gcode)",
    )
    args = p.parse_args()

    if args.out is None:
        build_dir = LESSON_DIR / "build"
        build_dir.mkdir(exist_ok=True)
        args.out = build_dir / f"spacer_od{args.od}_id{args.id}.gcode"
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)

    material = load_material(args.material)
    gcode = generate_gcode(args.od, args.id, material)
    args.out.write_text(gcode)
    print(f"-> wrote {args.out}")


if __name__ == "__main__":
    main()
