"""GCode emission + preview rendering for orpot.

Self-contained, but the GRBL/laser conventions are ported verbatim from the
sibling jigsawzall/emitter.py so the machine behavior is identical:

  - $32=1 laser mode, G21 mm, G90 absolute
  - STATIC M3 constant power at 100% (this weak diode under-fires on M4 dynamic)
  - a front-loaded warmup wiggle at the START of every cut so the beam reaches
    full power before it bites (diode cold-start ~1s ramp)
  - point decimation so no emitted segment is shorter than a floor

Coordinates arrive already in machine mm (Y-up, positive) from spiral.py, so
there is no image-pixel flip here (unlike jigsaw).
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import yaml
from PIL import Image, ImageDraw, ImageFont
from shapely.geometry import Polygon

REPO_ROOT = Path(__file__).resolve().parent

# Diode cold-start ramp: time to reach full optical power after the beam fires.
# Fixed for this machine regardless of material. Front-loaded as an out-and-back
# wiggle over the start of each cut (half forward, half back).
WARMUP_MS = 1000.0

_PREAMBLE = (
    "$32=1   ; GRBL laser mode",
    "G21     ; mm",
    "G90     ; absolute",
    "M5      ; laser off",
    "G0 X0 Y0",
    "",
)


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------


def load_material(material_id: str) -> dict:
    """Look up a material by id in profiles/laser_materials.yaml."""
    path = REPO_ROOT / "profiles" / "laser_materials.yaml"
    with path.open() as f:
        materials = yaml.safe_load(f)
    for m in materials:
        if m.get("id") == material_id:
            return m
    available = ", ".join(sorted(m.get("id", "?") for m in materials))
    raise SystemExit(f"unknown material: {material_id}. Available: {available}")


# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------


def _header(title: str, material_id: str, extra: list[str] | None = None) -> list[str]:
    out = [f"; {title}", "; generated by orpot/emit.py"]
    if extra:
        out += [f"; {e}" for e in extra]
    out += [
        ";",
        ";HEAD: laser",
        f";MATERIAL: {material_id}",
        ";LASER_MODE: static  (M3 — dwell-burn-through risk if motion stalls)",
        "",
        *_PREAMBLE,
    ]
    return out


# ---------------------------------------------------------------------------
# Path helpers (ported verbatim from jigsawzall/emitter.py)
# ---------------------------------------------------------------------------


def decimate_min_segment(
    pts: list[tuple[float, float]], min_seg_mm: float
) -> list[tuple[float, float]]:
    """Drop intermediate points that would create a segment shorter than
    min_seg_mm. Endpoints are always preserved (so closed rings stay closed)."""
    if min_seg_mm <= 0 or len(pts) < 3:
        return pts
    out = [pts[0]]
    for p in pts[1:]:
        lx, ly = out[-1]
        if math.hypot(p[0] - lx, p[1] - ly) >= min_seg_mm:
            out.append(p)
    if out[-1] != pts[-1]:
        if len(out) >= 2:
            out.pop()
        out.append(pts[-1])
    return out


def _points_up_to(coords, dist):
    """Polyline from coords[0] forward along coords until arclength `dist`."""
    out = [coords[0]]
    acc = 0.0
    for a, b in zip(coords, coords[1:]):
        seg = math.hypot(b[0] - a[0], b[1] - a[1])
        if acc + seg >= dist and seg > 1e-9:
            t = (dist - acc) / seg
            out.append((a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1])))
            return out
        out.append(b)
        acc += seg
    return out


def _warmup_wiggle(coords, warmup_mm):
    """Front-loaded diode warmup: motion points (starting AND ending at
    coords[0]) that trace back and forth over the START of the path so the laser
    reaches full power by the time it returns to coords[0]. Returns [] if
    warmup_mm <= 0."""
    if warmup_mm <= 0 or len(coords) < 2:
        return []
    total = 0.0
    for a, b in zip(coords, coords[1:]):
        total += math.hypot(b[0] - a[0], b[1] - a[1])
    if total <= 1e-9:
        return []
    half = warmup_mm / 2.0
    if total >= half:  # long enough: forward half, back to start
        fwd = _points_up_to(coords, half)
        return fwd[1:] + list(reversed(fwd))[1:]
    # short path: oscillate end-to-end (round trips return to start) until covered
    trips = max(1, math.ceil(warmup_mm / (2.0 * total)))
    seq = []
    for _ in range(trips):
        seq += list(coords[1:]) + list(reversed(coords))[1:]
    return seq


# ---------------------------------------------------------------------------
# Cut GCode
# ---------------------------------------------------------------------------


def _exterior_coords(poly: Polygon) -> list[tuple[float, float]]:
    return [(float(x), float(y)) for x, y in poly.exterior.coords]


def emit_cut_gcode(
    parts: list[tuple[str, Polygon]],
    material: dict,
    title: str,
    cfg,
    feed_override: int | None = None,
    power_percent: float | None = None,
) -> str:
    """Emit static-M3 cut GCode for one or more spiral parts.

    Each part is a single simply-connected polygon; we cut its exterior ring,
    with a front-loaded warmup wiggle at the start and `passes` repeats. Points
    are decimated to cfg.min_segment_mm. Coordinates are already machine mm."""
    laser = material["laser"]
    pct = power_percent if power_percent is not None else laser["power_percent"]
    power_s = int(round(pct * 10))
    feed = feed_override if feed_override is not None else laser["feed_mm_per_min"]
    passes = laser["passes"]

    warmup_mm = WARMUP_MS / 60000.0 * feed  # mm covered during the ramp at this feed

    extra = [
        "orpot phase-1 spirals: cut flat, then lift an end to coil (flex test)",
        "centerline cut of each ribbon exterior; kerf becomes clearance",
        "ASSUMES Z already at focal height in your WCS",
        f"warmup: {WARMUP_MS:.0f}ms = {warmup_mm:.1f}mm out-and-back at F{feed}",
    ]
    lines = _header(title=title, material_id=material["id"], extra=extra)

    for name, poly in parts:
        pts = decimate_min_segment(_exterior_coords(poly), cfg.min_segment_mm)
        if len(pts) < 3:
            continue
        x0, y0 = pts[0]
        lines.append(f"; --- {name} spiral ({len(pts)} pts) ---")
        lines.append(f"G0 X{x0:.3f} Y{y0:.3f}")
        lines.append(f"M3 S{power_s}")
        lines.append(f"F{feed}")
        for wx, wy in _warmup_wiggle(pts, warmup_mm):
            lines.append(f"G1 X{wx:.3f} Y{wy:.3f}")
        for pass_n in range(passes):
            if passes > 1:
                lines.append(f"; pass {pass_n + 1} of {passes}")
            for x, y in pts[1:]:
                lines.append(f"G1 X{x:.3f} Y{y:.3f}")
        lines.append("M5")
        lines.append("")

    lines += ["G0 X0 Y0", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Preview (PIL raster; SVG opt-in). Mirrors jigsawzall's render approach.
# ---------------------------------------------------------------------------


def _load_font(size: int):
    for name in ("Arial.ttf", "DejaVuSans.ttf", "Helvetica.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _poly_rings(poly: Polygon) -> list[list[tuple[float, float]]]:
    rings = [[(float(x), float(y)) for x, y in poly.exterior.coords]]
    for interior in poly.interiors:
        rings.append([(float(x), float(y)) for x, y in interior.coords])
    return rings


def render_preview(
    parts: list[tuple[str, Polygon]],
    out_stem: Path,
    title: str,
    write_svg: bool = False,
) -> tuple[Path, Path | None]:
    """Write a PNG (and optionally SVG) of the part outlines. Returns
    (png_path, svg_path_or_None). Y is flipped so up is +Y like the machine."""
    pad = 10.0
    all_rings = [ring for _, p in parts for ring in _poly_rings(p)]
    xs = [x for ring in all_rings for x, _ in ring]
    ys = [y for ring in all_rings for _, y in ring]
    maxx, maxy = max(xs), max(ys)
    vw = maxx + 2 * pad
    vh = maxy + 2 * pad

    png_path = out_stem.with_suffix(".png")
    svg_path = out_stem.with_suffix(".svg")

    def fy(y: float) -> float:
        return maxy - y + pad

    if write_svg:
        svg = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{vw}mm" '
            f'height="{vh}mm" viewBox="0 0 {vw} {vh}">',
            f'<rect x="0" y="0" width="{vw}" height="{vh}" fill="white"/>',
            f"<title>{title}</title>",
        ]
        for ring in all_rings:
            pts = " ".join(f"{x + pad:.3f},{fy(y):.3f}" for x, y in ring)
            svg.append(
                f'<polyline points="{pts}" fill="none" stroke="#b03020" '
                f'stroke-width="0.3"/>'
            )
        svg.append("</svg>")
        svg_path.write_text("\n".join(svg))

    scale = max(4, int(900 / max(vw, vh)))
    W, H = int(vw * scale), int(vh * scale)
    img = Image.new("RGB", (W, H), (255, 255, 255))
    d = ImageDraw.Draw(img)

    def px(x: float, y: float) -> tuple[float, float]:
        return ((x + pad) * scale, (maxy - y + pad) * scale)

    for ring in all_rings:
        d.line([px(x, y) for x, y in ring], fill=(176, 48, 32), width=2)
    d.text(
        (pad * scale, 2), title, fill=(20, 20, 20), font=_load_font(max(12, scale * 3))
    )
    img.save(png_path, "PNG", optimize=True)
    return png_path, (svg_path if write_svg else None)


# ---------------------------------------------------------------------------
# 3D assembly sketch (orthographic wireframe; no extra deps)
# ---------------------------------------------------------------------------


def _project(pts: np.ndarray, az_deg: float, el_deg: float) -> np.ndarray:
    """Rotate 3D points about Z by az, then about X by el, and orthographically
    keep (x, z) as screen (u, v up). Returns Nx3 array [u, v, depth]; depth is
    the post-rotation Y (larger = further from camera)."""
    az, el = math.radians(az_deg), math.radians(el_deg)
    x, y, z = pts[:, 0], pts[:, 1], pts[:, 2]
    x1 = x * math.cos(az) - y * math.sin(az)
    y1 = x * math.sin(az) + y * math.cos(az)
    z1 = z
    y2 = y1 * math.cos(el) - z1 * math.sin(el)
    z2 = y1 * math.sin(el) + z1 * math.cos(el)
    return np.column_stack([x1, z2, y2])


def render_assembly_sketch(
    helices: list[tuple[str, dict]],
    cfg,
    out_stem: Path,
    title: str,
    base_r: float,
    az_deg: float = 32.0,
    el_deg: float = 22.0,
) -> Path:
    """Quick 3D wireframe sketch of the assembled pot: each spiral's inner/outer
    rails plus ribbon rungs, and the base disc. Depth-sorted painter's order.
    Colors distinguish the two spirals. Vertical ribs are not drawn yet."""
    palette = {
        "bottom": (184, 118, 58),  # warm ochre
        "top": (176, 48, 32),  # brick red
    }
    rung_fade = 0.55  # rungs drawn lighter than rails

    # Collect drawable segments as (depth, (u1,v1), (u2,v2), color, width).
    segs: list[tuple] = []

    def add_polyline(p3: np.ndarray, color, width, step=1):
        pr = _project(p3, az_deg, el_deg)
        for i in range(0, len(pr) - step, step):
            a, b = pr[i], pr[i + step]
            segs.append(
                (
                    (a[2] + b[2]) / 2.0,
                    (a[0], a[1]),
                    (b[0], b[1]),
                    color,
                    width,
                )
            )

    def lighten(c, f):
        return tuple(int(v + (255 - v) * f) for v in c)

    # Base disc outline (at z=0).
    ang = np.linspace(0, 2 * np.pi, 128)
    disc = np.column_stack(
        [base_r * np.cos(ang), base_r * np.sin(ang), np.zeros_like(ang)]
    )
    add_polyline(disc, (120, 120, 120), 2)

    for name, hx in helices:
        color = palette.get(name, (80, 80, 80))
        inner, outer = hx["inner"], hx["outer"]
        # Ribbon rungs (inner->outer) every ~8mm of travel to read as a surface.
        n = len(inner)
        stride = max(1, n // 48)
        for i in range(0, n, stride):
            rung = np.vstack([inner[i], outer[i]])
            add_polyline(rung, lighten(color, rung_fade), 1)
        # Rails on top.
        add_polyline(inner, color, 2)
        add_polyline(outer, color, 2)

    # Screen transform: fit all segment endpoints into a padded canvas.
    us = [u for _, (u, _), _, _, _ in segs] + [u for _, _, (u, _), _, _ in segs]
    vs = [v for _, (_, v), _, _, _ in segs] + [v for _, _, (_, v), _, _ in segs]
    minu, maxu, minv, maxv = min(us), max(us), min(vs), max(vs)
    pad = 30.0
    span = max(maxu - minu, maxv - minv)
    scale = (900 - 2 * pad) / span
    W = int((maxu - minu) * scale + 2 * pad)
    H = int((maxv - minv) * scale + 2 * pad) + 24  # room for the title

    def to_px(u, v):
        # v is up in world -> flip for image y.
        return (pad + (u - minu) * scale, 24 + pad + (maxv - v) * scale)

    img = Image.new("RGB", (W, H), (255, 255, 255))
    d = ImageDraw.Draw(img)
    # Painter's order: far (large depth) first.
    for _, p1, p2, color, width in sorted(segs, key=lambda s: -s[0]):
        d.line([to_px(*p1), to_px(*p2)], fill=color, width=width)
    d.text((pad, 6), title, fill=(20, 20, 20), font=_load_font(15))

    png_path = out_stem.with_suffix(".png")
    img.save(png_path, "PNG", optimize=True)
    return png_path
